### ISSUE TITLE
the comments/form.html file, the value of input(name=next) shoud be hardcode or take from context variable?

### ISSUE THREAD

**Issue by MusaZhou** [danirus/django-comments-xtd#107]
I want to redirect to my page after relpy the comment, so I append "next" query paramter behind /comment/reply, but in the upcoming reply.html page, I find that the input(name=next) is always equal to 'comments/sent', at first I thought there might be some problem of the query parameter appending. Later after dig into the source code. I found out that in our package, the overwriten comments/form.html page, doen't take the "next" parameter from context variable, instead it is hardcoded as "{% url 'comments-xtd-sent' %}", is this the designed behavior?

**Comment by danirus** [comment]
Hi @MusaZhou, this is a functionality provided by [django-comments](https://github.com/django/django-contrib-comments).  It's the default behaviour if you don't customize anything. The easiest thing would be to rewrite the form.html template and pass the `next` as an input within your form. You could also rewrite the `post/`  url in your project and pass the next parameter of your choice when it's missing in the form.

**Comment by MusaZhou** [comment]
Thanks alot @danirus . Really appreciate your answer. Thanks for your great work on this project.
