### ISSUE TITLE
How to support bootstrap4

### ISSUE THREAD

**Issue by ryo-ma** [danirus/django-comments-xtd#111]
Hi.
My project is using bootstrap4. but I think that django-comments-xtd must use bootstrap3.
There is icon issue. if it is using bootstrap4.
How to support bootstrap4.

**Comment by danirus** [comment]
Hi @ryo-ma, thanks for the remainder. I started last week to work on migrating to twbs 4.
I'm busy with other projects, but I admit that staying in version 3 is becoming an issue.
I hope/guess it will be done at the end of the month.

**Comment by ryo-ma** [comment]
Thank you for the reply. 
I'm looking forward to it.

**Comment by danirus** [comment]
Hi @ryo-ma, no problem, 
I'm too busy these days moving houses.
I will merge it in master at the end of November.
I hope it's still reasonable timing...

**Comment by ryo-ma** [comment]
Hi @danirus, It's ok.
Good luck with your move.

**Comment by danirus** [comment]
Fixed in 8ddb672.
