### ISSUE TITLE
Posting comment to localhost

### ISSUE THREAD

**Issue by wreeecks** [danirus/django-comments-xtd#113]
When i post a comment on my localhost it's posting/redirecting to the production site. Is there a configuration for this? Thanks!

**Comment by danirus** [comment]
Most probably because the site object (Sites app) pointing to the production URL.

**Comment by wreeecks** [comment]
Thank you for your reply. I'm using .env and different settings.py for my localhost and production. Can you please tell me where to change the site object url?

**Comment by wreeecks** [comment]
> In the database. In your settings you must have a `SITE_ID`, and that maps the running site to the Site object in your database. The redirection takes the `domain` attribute of the site object. If you are using a copy of the DB in production, you could add a new site for `localhost:8000` and use its ID in the `SITE_ID` in your settings. Or simply replace the domain value with `localhost:8000`.

Thank you! It's working now.
