### ISSUE TITLE
Changing the default permission policy for comments.

### ISSUE THREAD

**Issue by zugspitze** [danirus/django-comments-xtd#119]
Hi @danirus, I like this package a lot and want to use it. However, I have default permission set to `rest_framework.permissions.IsAuthenticated`. How can I change it to `rest_framework.permissions.AllowAny` for comments?

**Comment by danirus** [comment]
I gather you want to allow anonymous users to send comments. Is that right?
The app doesn't allow it without extra coding, implementing it won't be simple.
I like your hiking project btw. Nice that you are in Munich. :)

**Comment by zugspitze** [comment]
I understand, I would be glad to have some hands-on session. I will get back to you in your email regarding the possible dates.
