### ISSUE TITLE
bypass like and dislike confirmation page #support

### ISSUE THREAD

**Issue by ntmk** [danirus/django-comments-xtd#120]
I am having an issue adding the same functionality for the like / dislike button on the confirmation page to the thumbs up / down icons on the comment itself. It is quite possible I am overlooking where the actual update to the likedit_user arrays. If you can provide a hint in the right direction.

**Comment by danirus** [comment]
@ntmk, explain the situation further, I don't understand.

**Comment by ntmk** [comment]
@danirus I want to avoid being redirected to the like page. (django_comments_xtd/like.html)
 Instead I would like the user name to be appended to the `'likedit_users': [<User: user001>, <User: Nathan>]` array by clicking the thumbs up icon in the user_feedback.html.
The end goal is to have them comment and likes / dislikes update on page refresh without having to go through the comment confirmation. Hope this gives a better idea. Thanks for the response.

**Comment by danirus** [comment]
Then you have to use the react plugin with your project, and be logged in at the time you want to click on the thumbs up/down icon. Following the tutorial you might get there.
