### ISSUE TITLE
settings.SITE_ID?

### ISSUE THREAD

**Issue by gassan** [danirus/django-comments-xtd#124]
django.contrib.sites is one of required modules. Is it not posible to get the SITE_ID from request.site.pk?

**Comment by danirus** [comment]
It's possible, but `django.contrib.sites` is a dependency because django-comments-xtd extends django-contrib-comments which uses the `Site` model in the comment model.

**Comment by gassan** [comment]
therefore you could change line commetns_xtd.py:256 from
site__pk=settings.SITE_ID,
to
site__pk=request.site.pk
or sometheng speaks against it?

**Comment by danirus** [comment]
Sorry, I thought you wanted to get rid of the sites app.  
Of course you can replace them.

**Comment by danirus** [comment]
Your PR has been merged and the code is already available with v2.4.1.
Please, close the bug once you have verified it's been fixed.
Thanks again for your contribution.

**Comment by gassan** [comment]
It works. Thank you!
