### ISSUE TITLE
Akismet support and reCAPTCHA 

### ISSUE THREAD

**Issue by saileshkush95** [danirus/django-comments-xtd#129]
I also want to include reCAPTCHA and akismet in the comment form. But I've no idea how to implement it. Can we implement? Please let me know

**Comment by danirus** [comment]
The idea of sending a link via email that the user has to click on to validate the comment makes the need of reCAPTCHA and akismet pointless. The comment is not even stored in the DB unless the user clicks on the link.

If you still want to use reCAPTCHA and akismet you should disable comment confirmation by email and then follow their instructions.

**Comment by saileshkush95** [comment]
Thanks for quick response
