### ISSUE TITLE
"render_xtdcomment_tree" and "get_xtdcomment_tree" tags return incorrect result

### ISSUE THREAD

**Issue by hematinik** [danirus/django-comments-xtd#138]
The `render_xtdcomment_tree` and `get_xtdcomment_tree` tags return incorrect result if the first comment instance for any content has its `is_public` attribute set to False.

If below conditions meet you'll get incorrect results from the tags:

- The first comment instance for a certain content has replies
- The `is_public` attribute of the comment is set to False

in that case both tags skip the parent comments and return only children as a result (returning every comment with THREAD LEVEL > 0 )

both tags work as expected in other conditions for example when you set `is_public` to False on the second <XtdComment> instance and so on.

P.S.
I was unable to trace the issue but I could workaround this problem by creating dummy comments as the first comment on my content and skip them in my templates.

**Comment by danirus** [comment]
Thanks @hematinik, sorry for the late answer.

**Comment by danirus** [comment]
This issue has been fixed in v2.5.1.
Now, when setting is_public to False or when removing a comment (not deleting it from the DB), nested comments change their is_public to False, so that they are not retrieved or displayed.
