### ISSUE TITLE
Comment enabled only for logged in users.

### ISSUE THREAD

**Issue by sandeepbalagopal09** [danirus/django-comments-xtd#140]
Is there a settings available for the commenting option enabled only for the logged in users ?

**Comment by danirus** [comment]
You can implement that logic too.

We can see it how to do it using the [example projects](https://django-comments-xtd.readthedocs.io/en/latest/example.html] of the repository. But let me exactly know what you want to do. Do you want to disallow not registered users to send comments nor to see the list of comments? Also, are you planning to use the JavaScript plugin and the REST API (like in the comp example project)?

**Comment by sandeepimpressads** [comment]
I am using the Javascript plugin in the comp example. Currently anyone can comment by entering their details. What I want to do is commenting enabled only for logged in users. (Not list of comment, but submitting the form and comment). There will be the form shown with a textbox and button, but the button would say signup to comment and user redirected to the signup page.

**Comment by danirus** [comment]
It's a missing feature. 
I thought it was possible, but using the JavaScript plugin doesn't allow it. 
I will implemented it. 
Thanks for your report!

**Comment by bmull** [comment]
Adding a comment to follow along here. I'd love this too. I only want registered users to be able to comment / like / etc... Anyone else can read but basically the commenting feature is a logged in feature.

**Comment by danirus** [comment]
Now django-comments-xtd can be customize so that only registered users can post comments. It's explained in the docs, in the last section: **use cases**. Here is the link: [Only signed in users can comment](http://localhost:1025/usecases/only-signed-in-can-comment.html).
