### ISSUE TITLE
Avatar url and ssl

### ISSUE THREAD

**Issue by sandeepimpressads** [danirus/django-comments-xtd#150]
The Avatar url http://www.gravatar.com/ is causing the webpage not secure when the webpage is served using https. I tried changing the const avatar_url in commentform.jsx to https and compiled the code code using webpack but still the url is serving via http in detail page.

**Comment by danirus** [comment]
Hi @sandeepimpressads, just released v2.6.1 with a fix. Let me know if it doesn't work.

**Comment by sandeepimpressads** [comment]
Thanks. It worked.
