### ISSUE TITLE
New syntax for string formatting ?

### ISSUE THREAD

**Issue by sandeepbalagopal09** [danirus/django-comments-xtd#154]
I got an error from this line https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/api/serializers.py#L203 

Is this a new format in python ? I used do` raise Exception('Unexpected value for flag: {}'.format(value.flag))`

**Comment by danirus** [comment]
It's a python 3 formatting string. 
It's indeed an issue when using Python 2.7.

**Comment by sandeepimpressads** [comment]
> It's a python 3 formatting string.
> It's indeed an issue when using Python 2.7.

But I am using python 3.5.2. Is it a 3.6 syntax ?

**Comment by danirus** [comment]
It should support Python 3.5.

**Comment by sandeepimpressads** [comment]
It says support started from 3.6 https://www.python.org/dev/peps/pep-0498/

**Comment by danirus** [comment]
Yes, I meant, django-comments-xtd should support Python 3.5. 
I removed compatibility introducing that formatting style.
So it's a bug.

**Comment by danirus** [comment]
It's fixed in master. 
It will be released with the next v2.6.2.
Thanks for the report!

**Comment by danirus** [comment]
Thanks again for the report.
The issues has been resolved and fixed in PR #177.
