### ISSUE TITLE
How to create a comment using rest api in django-comments-xtd

### ISSUE THREAD

**Issue by KedarisettiSreeVamsi** [danirus/django-comments-xtd#155]
I have tried using /comments/api/comments/ and we are having problem with security_hash,honeypot can anyone help on how to post a comment

**Comment by KedarisettiSreeVamsi** [comment]
I used postman to send a comment to my app but it is giving me security_hash and honeypot and timezone as required_fields I have overrides timezone with django.utils.timezone but from other fields I am having this problem

**Comment by KedarisettiSreeVamsi** [comment]
Also for the api views we are getting CommentCreate doesn't have queryset

**Comment by KedarisettiSreeVamsi** [comment]
Added XtdComment.objects.all() for queryset in CommentCreate gave the API view but cannot resolve security_hash and honeypot

**Comment by KedarisettiSreeVamsi** [comment]
'''python
def good(x):
    return x
'''

**Comment by danirus** [comment]
So far it's not possible. It will be ready in the next release.

**Comment by kwhandy** [comment]
@KedarisettiSreeVamsi have you try this? https://github.com/timonweb/django-ajax-comments-xtd

**Comment by danirus** [comment]
Pull request #181 implements the fix for this issue.
The fix will be wrapped in v2.7.0 in a few days. 
The web API docs have been extended to cover the case.
Thanks @KedarisettiSreeVamsi for sending it.
