### ISSUE TITLE
Comments polling is not working

### ISSUE THREAD

**Issue by ashwani99** [danirus/django-comments-xtd#156]
I have been following the `django-comments-xtd` [tutorial](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#javascript-plugin) from the docs. I am not able to see the new comments update alert appear. I have also tried checking for the XHR requests, but it seems for any value of `poll_interval`, the new comments are not getting polled at all

**Comment by ashwani99** [comment]
Apparently, the prop name `poll_interval` is a typo. It should be `polling_interval`. 

Will send a PR for this :100:

**Comment by danirus** [comment]
Thanks @ashwani99, indeed there's a mix of poll and polling over the docs and the code.

**Comment by ashwani99** [comment]
@danirus I have added a PR for this already #157
