### ISSUE TITLE
base.html template not found error

### ISSUE THREAD

**Issue by rajnishdahiya** [danirus/django-comments-xtd#165]
---- ERROR TRACE BEGINS ---
_Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.filesystem.Loader: X:\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: X:\public\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\django\contrib\admin\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\django\contrib\admindocs\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\django\contrib\auth\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\django_comments_xtd\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\django_comments\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\contrib\forms\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\contrib\modeladmin\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\contrib\redirects\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\contrib\styleguide\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\embeds\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\sites\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\users\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\snippets\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\documents\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\images\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\search\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\admin\templates\base.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wagtail\core\templates\base.html (Source does not exist)

Template error:
In template C:\Users\csera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\django_comments_xtd\templates\django_comments_xtd\base.html, error at line 1
   base.html
   1 :  {% extends "base.html" %} 
   2 :_ 
---- ERROR TRACE ENDS ---
I think django_comments_xtd/base.html is missing "comments/" extends file path.

`{% extends "base.html" %}`

it works when I change it to

`{% extends "comments/base.html" %}`

**Comment by danirus** [comment]
django-comments-xtd doesn't have to provide a base.html template.

**Comment by rajnishdahiya** [comment]
ok. But it is providing one. Shouldn't we push a commit removing this base.html then?
