### ISSUE TITLE
 High expectation on request

### ISSUE THREAD

**Issue by ogurec-ogurec** [danirus/django-comments-xtd#169]
I have the following problem:

As soon as I add the **PostCommentModerator** class to models.py (redefine), the processing/loading time of my request for _comment/api/comments_ grows to **25 seconds**.  As soon as I remove this class, then everything works fine.

> Waiting (TTFB) | ​ 23.80 s

I use: Postresql, django version 3.0.5, standard server when installing Django, localhost (windows 7)

What can be done about this? I would be grateful for any help

**Comment by danirus** [comment]
That's too much. It has no sense. I'll check later. 
Meanwhile, it would be good if you could try the same setup in a Linux machine.

**Comment by ogurec-ogurec** [comment]
Indeed, the problem was on my side (duplicated models). Thanks you
