### ISSUE TITLE
`user_moderator` field is `false` for non superusers in Web API

### ISSUE THREAD

**Issue by ashwani99** [danirus/django-comments-xtd#171]
When fetching comments, the `user_moderator` field comes `false` for all non superuser accounts. For superuser accounts, since they have all permissions, its `true` 

To reproduce, make a GET request to [retrieve-comment-list](https://django-comments-xtd.readthedocs.io/en/latest/webapi.html#retrieve-comment-list) endpoint.

**Comment by danirus** [comment]
The PR #178 implements the fix and closed the bug. 
I will wrap this fix as part of the 2.6.3 with other issues. 
Whenever you test it, if you find that the issue is still present, please, reopen it.
@ashwani99, thanks again for your report!
