### ISSUE TITLE
 Change language

### ISSUE THREAD

**Issue by ogurec-ogurec** [danirus/django-comments-xtd#174]
How can I change the language? For example, in Russian. In the settings added:

```
LANGUAGE_CODE = 'ru'

LANGUAGES = (
    ('ru', 'Russian'),
)

```

Added 1 a file **_django.po (rus)_** to the folder:

`..\Lib\site-packages\django_comments_xtd\locale\ru\LC_MESSAGES\django.po`

Restarted the server, but nothing has changed.

**Comment by danirus** [comment]
You have to use the `compilemessages` command of Django. Read the Internationalization page of the docs: [here](https://django-comments-xtd.readthedocs.io/en/latest/i18n.html). Remember that the JavaScript plugin uses its own `djangojs.po` as oppose to the `django.po` used by the backend. 

There's already a `django.po` for Russian in django-comments-xtd. It was added by @MikerStudio a month ago. However there's no translation for the plugin yet.

On changing the language,  if you want your site to be in Russian, change the `LANGUAGE_CODE` setting in your `settings.py` module:

    LANGUAGE_CODE = 'ru'

If you want to support multiple languages, I recommend you to read the pages under the [Internationalization](https://docs.djangoproject.com/en/3.0/topics/i18n/) topic in the office Django site, it's a lot, but it's worth reading. You can also see how it is done in the example comp site that comes with django-comments-xtd:

- In your `settings.py` module:
  - Add the `LANGUAGES` setting and `LANGUAGE_CODE` (as you do already, but add more languages).
  - Add `USE_I18N = True`
- In your `urls.py` module:
  - Add `re_path(r'^i18n/', include('django.conf.urls.i18n'))`
- In your templates:
  - Search and follow the word `LANGUAGE` in [base.html](https://github.com/danirus/django-comments-xtd/blob/master/example/comp/templates/base.html) in the comp project.

**Comment by ogurec-ogurec** [comment]
thanks
