### ISSUE TITLE
django.contrib.comments is deprecated, should depend on django-contrib-comments

### ISSUE THREAD

**Issue by wolfhechel** [danirus/django-comments-xtd#18]
Since django.contrib.comments has been deprecated and will be removed before Django 1.8 now might be a good idea to merge over to django "excontrib" comments instead.

I have just recently started using comments xtd however so I don't know if there's another plan for this? If not I'd be happy to write together a pull request for this.

**Comment by kim07** [comment]
thanks helped me a lot

**Comment by bufke** [comment]
Any updates? I'm already using the pull request version. I'd be happy to help maintain and do a pypi release if need be.

**Comment by wolfhechel** [comment]
Very sorry for the lack of progress here, I'm not using comments-xtd after moving to disqus so I haven't had any time to support this.

@bufke You're more then welcome to take over the PR for this as I'm certain I'm not going to find any open time slot for myself to do this. I know the fix is small and all but I have tons of these minor things I need to fix, and this has been my lowest priority for some time and will probably continue to be so for an undetermined time.

**Comment by danirus** [comment]
Django 1.8, released the 1st of April, does not come any longer with `django.contrib.comments`. If you are already using 1.8 you must install [django-contrib-comments](http://django-contrib-comments.readthedocs.org/en/latest/) as a replacement. For previous versions you don't need to. 

I'm sorry, I didn't have much time to keep django-comments-xtd updated. It's not lack of interest, I use it in many websites. It's basically parenthood and a very busy work schedule. I will get time again soon and will look into this as it deserves. Won't be later than the end of June.

**Comment by bufke** [comment]
What's left to do @wolfhechel just support for previous versions. django-contrib-comments claims 1.5 support.

@danirus I'd be happy to help review and merge pull requests and do pypi releases if you'd like. Totally understand. I'm using this for a work project.

**Comment by wolfhechel** [comment]
As we've discussed before the one thing that needs to be done is to have conditional checks wether it should be using the contrib module or the separate django-contrib-comments.

I was considering letting it lookup the INSTALLED_APPS to see which is installed,
but considering we're now already in Django 1.8 I think it should probably just try to default on django-contrib-comments and fallback to django.contrib.comments if it fails.

**Comment by wolfhechel** [comment]
Also, you might want to collaborate with @agilosoftware on this since they've also [forked](https://github.com/agilosoftware/django-comments-xtd/commit/d948a61f3b21f83655f6604423f3f400a4b84c22) my PR to apply a Django 1.8 fix for the changes in the transaction API.

**Comment by sterago** [comment]
yes, I can confirm our fork is working with Django 1.8 without problems (nor warnings) so far

**Comment by danirus** [comment]
I'm working on this issue as of right now. Hope to have it fixed within the week. The tricky part is not to make it work just for Django 1.8 but for Django 1.4.20 (the LTS), 1.7.7, and 1.8, under Python 2.7 and Python 3.4 (only Django 1.7.7 and above).

If you are in a hurry and only need this fixed for Django 1.8, I suggest you to clone this repository and merge @wolfhechel's pull request. Otherwise, please, wait a few more days.

**Comment by garrish27** [comment]
<html>
<body>
<ul>
<li>
<a href="http://www.ismart4u.com/catagory/books/">Text Books</a>
</li>
<li>
<a href="http://www.ismart4u.com/catagory/education/">Games</a>
</li>
<li>
<a href="http://www.ismart4u.com/catagory/islamic_apps/">Electronic Gadgets</a>
</li>
<li>
<a href="http://www.myiqraapps.com/">Islamic Apps</a>
</li>
<li>
<a href="http://www.iqra.com.hk/">Islamic Devices</a>
</li>
</ul>
</body>
</html>

**Comment by danirus** [comment]
Fixed with 4a05931944dd5b1f0c506fccc9d301a4b6cce8f4
