### ISSUE TITLE
requests are automatically sent

### ISSUE THREAD

**Issue by ogurec-ogurec** [danirus/django-comments-xtd#182]
I am on the post page with comments, doing nothing (I am in view mode ), but requests are automatically sent every two seconds. This is normal?

![bag3](https://user-images.githubusercontent.com/66796268/89714887-b368ce00-d92c-11ea-916d-e32db2b781d2.gif)

How can I make it so that requests are only sent on page reload?

**Comment by danirus** [comment]
Yes, it's normal.
Edit the HTML template where you load the plugin. You must have something like:

    <script>
     window.comments_props = {% get_commentbox_props for object %};
     window.comments_props_override = {
       allow_comments: {%if object.allow_comments%}true{%else%}false{%endif%},
       allow_feedback: true,
       show_feedback: true,
       allow_flagging: true,
       polling_interval: 5000
     };
    </script>

Change the `polling_interval` to `0`. That will make it.

**Comment by ogurec-ogurec** [comment]
Thank you, then I have two questions. First: Why are requests being sent?
Second: Will it create a load (requests) on the server with a large number of users?

Thank you in advance

**Comment by danirus** [comment]
The JavaScript plugin uses polling to check whether there are new comments. It's explained [here](http://localhost:1025/tutorial.html#load-the-plugin) in the Tutorial. Whether it creates or not a high number of requests to your server depends on how you set it up and how your visitors behaves.
