### ISSUE TITLE
Require registration to post

### ISSUE THREAD

**Issue by jimkring** [danirus/django-comments-xtd#186]
Hi! Great application!

What's the recommended way to require a user be logged in (registered) in order to post comments? If they aren't signed in, I'd like to redirect them to the login page.

Thanks!

**Comment by danirus** [comment]
Thanks @jimkring. In the very last version of the docs I added such [use case](https://django-comments-xtd.readthedocs.io/en/latest/usecases/only-signed-in-can-comment.html).

**Comment by jimkring** [comment]
Hi @danirus. That's fantastic! It's great that you took the time to document these use cases.

Suggestion: Maybe add the `'who_can_post': 'users'` to the _[tutorial >> commenting](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#commenting-options)_ options section, so that we're exposed to this setting early on in the install/setup process.

```
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    'default': {
        'allow_flagging': False,
        'allow_feedback': False,
        'show_feedback': False,
        'who_can_post': 'users'  # << maybe add this line to the 'tutorial >> commenting' options section
    }
}
```

I've created an issue for this suggestion:
https://github.com/danirus/django-comments-xtd/issues/189
