### ISSUE TITLE
Errors until I installed django-avatar application - is it required?

### ISSUE THREAD

**Issue by jimkring** [danirus/django-comments-xtd#188]
I noticed that I was getting errors until I installed django-avatar. Is this supposed to be a requirement of django_comments_xtd? If so, it should probably be included in the installation / getting started documents. Thanks!

**Comment by danirus** [comment]
No, django-avatar is not a requirement.
If you can reproduce the issue, please, post it here and I'll look into it.

**Comment by jimkring** [comment]
I tried to reproduce this, but I cannot.  I think I caused this error. Thanks for letting me know.

**Comment by jimkring** [comment]
I just reproduced the issue, I think -- it happens when I try to post a comment.

Inside of `preview.html` it loads `avatar_tags` (on line 3):

`django_comments_xtd/templates/comments/preview.html`

```
{% extends "django_comments_xtd/base.html" %}
{% load i18n %}
{% load avatar_tags %}
{% load comments_xtd %}
 
{% block title %}{% trans "Preview your comment" %}{% endblock %}
 
{% block content %}
<div class="container">
<div class="mb-4">
<h3 class="text-center">{% trans "Preview your comment" %}</h3>
<hr/>
</div>
```

**Comment by jimkring** [comment]
It seems like I can work around this by copying this template over into my project and then removing that `{% load avatar_tags %}` line -- everything seems to work OK without it, which means it was probably left over from some experimentation or creating a demo.

**Comment by danirus** [comment]
That's a bug. I added it by mistake a few days ago while writing the docs. Thanks for the catch!

**Comment by danirus** [comment]
This bug has been fixed already and will be released as part of v.2.7.1.
Thanks again @jimkring for the quick catch!
