### ISSUE TITLE
Add who_can_post setting to the Commenting Options section of the Tutorial documentation

### ISSUE THREAD

**Issue by jimkring** [danirus/django-comments-xtd#189]
It would be nice to learn about the `'who_can_post': 'users'` option when going through the _[tutorial >> commenting](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#commenting-options)_ options section, so that developers are exposed to this setting early on in the install/setup process.

```
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    'default': {
        'allow_flagging': False,
        'allow_feedback': False,
        'show_feedback': False,
        'who_can_post': 'users'  # << maybe add this line to the 'tutorial >> commenting' options section
    }
}
```

**Comment by danirus** [comment]
That's a good point, thank you!

**Comment by danirus** [comment]
It's already updated but only when browsing the documentation of the version labelled as *latest*:
https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#commenting-options
