### ISSUE TITLE
How to get comment count for an individual object 

### ISSUE THREAD

**Issue by jimkring** [danirus/django-comments-xtd#192]
I see [here in the docs](https://django-comments-xtd.readthedocs.io/en/latest/templatetags.html?highlight=count#tag-get-xtdcomment-count) that we can get the comment count for a specific model (object type)

`{% get_xtdcomment_count as [varname] for [app].[model] [[app].[model] ...] %}`

I'm trying to get the comment count for an individual object.  I'm thinking that I may need to implement that myself, since I don't see it readily in any of the template tags.

Any good solution for this?

**Comment by rgutierrez-cotech** [comment]
You have to use the template tag from `django-contrib-comments`, which is
```
{% get_comment_count for object [as varname] %}
```

**Comment by danirus** [comment]
Thanks for your answer, @rgutierrez-cotech. I think it solves the question.
I enabled Discussions in this repository. It seems better to handle this kind of questions.
I'm closing this issue now. If you need to reopen it, please, post it in Discussions. Thank you!
