### ISSUE TITLE
Adding the "reply" link?

### ISSUE THREAD

**Issue by deronsizemore** [danirus/django-comments-xtd#20]
I've been looking through the docs and I can't seem to find much on adding a "reply" link to each comment so threaded comments can be used. I'm sorry if this is obvious, but I'm not seeing it. Can anyone point me in the right direction? Seems I've got everything else working, just want to mess around with threads.

**Comment by kim07** [comment]
thanks helped me a lot

**Comment by danirus** [comment]
Hi @deronsizemore, I hope you get it working. Sorry for vanishing.
I do agree, that having the reply page apart doesn't look good.
I will start soon writing a jQuery plugin to handle comment interaction with Ajax. I'll do it in the develop branch, just in case you want to follow up or give feedback.

**Comment by deronsizemore** [comment]
Sounds good. Thanks!
