### ISSUE TITLE
Follow-up Tick Box customizable via a setting

### ISSUE THREAD

**Issue by danirus** [danirus/django-comments-xtd#206]
Create a new setting to customize the default value of the follow-up field in the comment form.
The new setting could be called `COMMENTS_XTD_DEFAULT_FOLLOW_UP` and it could be `True` or `False`.

**Comment by drholera** [comment]
Hello @danirus, could I take a look at this issue?

As I understood right if the `COMMENTS_XTD_DEFAULT_FOLLOW_UP` setting is switched to `False` we shouldn't display the "Follow up" checkbox, am I right? 

Thanks

**Comment by danirus** [comment]
Hi @drholera,
Yes, you can adopt it. Please add some unit tests too.
The idea is to use it along with the `XtdCommentForm`, to provide a default value for the `followup` field.
To avoid displaying the field in the form the user can edit/replace the `form.html` template and the form validation will accept the value given in the `COMMENTS_XTD_DEFAULT_FOLLOW_UP` setting, because the field is not required.

**Comment by drholera** [comment]
Hello @danirus 
The [PR](https://github.com/danirus/django-comments-xtd/pull/254) is added, could you please check if it's what we expect here?

**Comment by danirus** [comment]
Hi @drholera, thanks for adopting it. 
You have implemented something different.

This new setting is only to feed the form `followup` field with a default value. There is no need to change the template. Adopters of this app can change the template at will if they want to hide the field. So the implementation is far easier than what you have done. It requires changes in the `defaults.py` module (to include the new setting, with the default value to False to not break backward compatibility), the `form.py` module (to feed the `followup` field with the default attribute coming from this setting) and a couple of tests to check how the form is rendered when the setting takes `True` and `False` values.

**Comment by drholera** [comment]
Thank you for the clarification. I've created a new [PR](#270), I think now it should be better. Could you please check if it's what we need? 

In this PR we have a new setting `COMMENTS_XTD_DEFAULT_FOLLOW_UP` with the default value `False`. If we'll switch it to `True` - the 'followup' checkbox on the comment form will become checked. Also added tests there.

**Comment by ogurec-ogurec** [comment]
I understand correctly that after setting the COMMENTS_XTD_DEFAULT_FOLLOW_UP = True setting, the Notify about subsequent comments checkbox should be enabled?
After updating the setting, the checkmark is still unchecked :(

**Comment by drholera** [comment]
You should use the `COMMENTS_XTD_DEFAULT_FOLLOWUP ` setting, without the underscore.

**Comment by danirus** [comment]
Sorry about that.
We forgot to modify the [docs](https://django-comments-xtd.readthedocs.io/en/latest/settings.html) to mention the new setting.

**Comment by drholera** [comment]
Hello @danirus 
Added #283, could you please check if it's enough or we need to add some additional info?

**Comment by ogurec-ogurec** [comment]
Thanks!, added setting to setting.py
`COMMENTS_XTD_DEFAULT_FOLLOWUP = True`
But all the same, the checkmark in the comments is inactive (

**Comment by danirus** [comment]
Can you run your project's shell command and run this code?

    >>> from django_comments_xtd import get_form, get_version
    >>> get_version()
    '2.8.3'
    >>> get_form()
    django_comments_xtd.forms.XtdCommentForm

What do they return? If the version is older than [2.8.3](https://github.com/danirus/django-comments-xtd/releases/tag/2.8.3), the setting was not implemented yet. It's only available as of 2.8.3. If on the other hand the form is a class other than `django_comments_xtd.forms.XtdCommentForm`, the class you would be using might implement the followup field without taking into account the new setting.

Let us know.

**Comment by danirus** [comment]
@ogurec-ogurec, this questions would better be in Discussions.
