### ISSUE TITLE
Localization in form.py

### ISSUE THREAD

**Issue by sahandsepanta** [danirus/django-comments-xtd#21]
Hello contributors,
I'm trying to run your code under Django 1.6 and Python 3.3.4. One issue that I see is that in forms.py you put some fields in small letters so it won't get translated in view. I can name a few :  
<code>
self.fields['email'] = forms.EmailField(
            label=_("Email"), help_text=_("Required for comment verification"),
            widget=forms.TextInput(attrs={'placeholder':_('email')})
            )
</code>
placeholder email should change to Email.

And here 
<code>
self.fields['comment'] = forms.CharField(
            label= _("Comment"),
            widget=forms.Textarea(attrs={'placeholder':_('comment')}), 
            max_length=settings.COMMENT_MAX_LENGTH)
</code>
 I manually added label since your code is missing that. Am I right about that?

One tiny question, I have used git for personal project, but if I want to contribute to the current project what should I do?

**Comment by danirus** [comment]
Sorry for vanishing @sahandsepanta.
You can submit a Pull Request. You must first clone the repository, then make your changes in your copy, test that everything works and send a pull request so that I can see your changes. I'll be glad to review them.
