### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by omaraltayyan** [danirus/django-comments-xtd#222]
is there a method by which we can control access to  the API to private comments, imagine having a thread in a closed private forum page, is anyone who can guess object and content type IDs will be able to get the comments on any entity on any site that uses this library?

**Comment by omaraltayyan** [comment]
note that i am using the provided React plugin not Django templates

**Comment by danirus** [comment]
Yes. You have control over it via the authentication and permissions of [django-rest-framework](https://www.django-rest-framework.org/). 

If you want to prevent anyone from using the API, allowing access only to registered users, you could use the following in your settings module:

    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework.authentication.SessionAuthentication',
        ],
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.IsAuthenticated',
        ]
    }

**Comment by omaraltayyan** [comment]
> Yes. You have control over it via the authentication and permissions of [django-rest-framework](https://www.django-rest-framework.org/).
> 
> If you want to prevent anyone from using the API, allowing access only to registered users, you could use the following in your settings module:
> 
> ```
> REST_FRAMEWORK = {
>     'DEFAULT_AUTHENTICATION_CLASSES': [
>         'rest_framework.authentication.SessionAuthentication',
>     ],
>     'DEFAULT_PERMISSION_CLASSES': [
>         'rest_framework.permissions.IsAuthenticated',
>     ]
> }
> ```

very helpful thanks!!
