### ISSUE TITLE
Post comments with REST Web API without DRF not working in versions >2.6.2

### ISSUE THREAD

**Issue by TommasoAmici** [danirus/django-comments-xtd#229]
In version 2.7.0 this was added 

>support to allow Django REST Framework authentication classes

The old workflow with `timestamp` and `security_hash` doesn't seem to work on versions after 2.6.2. Is this behavior intended?

**Comment by danirus** [comment]
No, it should work provided an empty `honeypot` field, a valid `timestamp` and `security_hash`.
Version 2.7.0 allows posting comments with the REST API without those fields, but has to work with them too.

**Comment by TommasoAmici** [comment]
Ok, I've managed to make it work, thanks. This is what I changed:

```diff
const data: CommentPayload = {
      object_pk: commentsProps.form.object_pk,
      content_type: commentsProps.form.content_type,
-     reply_to: commentID !== null ? commentID : "0",
+     reply_to: commentID !== null ? parseInt(commentID) : 0,
-     honeypot: "",
    };
```

**Comment by danirus** [comment]
Thanks for your feedback!
You shouldn't have to remove the `honeypot` field. So it's a bug.
