### ISSUE TITLE
Comments do not post: raises page not found error 

### ISSUE THREAD

**Issue by dtdibaba** [danirus/django-comments-xtd#239]
When I try to post comment or preview, it raises Page not found error.
It shows this URL http://127.0.0.1:8000/comments/post/. 

I installed both django_comments and django_comments_xtd
Added 
'django_comments_xtd',
 'django_comments',
to INSTALLED_APPS
    
I included path('comments/, include(django.comments_xtd.urls))  in my project and app urls

Added the CommentModerator class to my model.
And added 

{% load comments %}
{% load comments_xtd %}

....

<div class="card-body">
  {% if new_comment %}
  <div class="alert alert-success" role="alert">
    Your comment is awaiting moderation
  </div>
  {% else %}
  <h3>Leave a comment</h3>
  <form method="post" style="margin-top: 1.3em;">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
  </form>
  {% endif %}
</div>

{% if comment_count %}
<hr/>
<div class="comments">
  {% render_comment_list for post %}
</div>
{% endif %}

{% get_comment_count for post as comment_count %}
<div class="py-4 text-center>
  <a href="{% url 'blog:post_list' %}">Back to the post list</a>
  &nbsp;&sdot;&nbsp;
  {{ comment_count }} comment{{ comment_count|pluralize }}
  ha{{ comment_count|pluralize:"s,ve"}} been posted.
</div>

{% if post.allow_comments %}
<div class="comment">
  <h4 class="text-center">Your comment</h4>
  <div class="well">
    {% render_comment_form for post %}
  </div>
</div>
{% endif %}

{% if comment_count %}
<ul class="media-list">
  {% render_xtdcomment_tree for object %}
</ul>
{% endif %}

before the {% endblock % 
tags in my detail.html template

I checked in my project lib/python3.8/site-packages/ folder and did not see django_comments_xtd folder.
So, I cloned it from Git but it did not work.

I followed this tutorial: https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html
Am I supposed to copy the django_comments templates to my project templates?
Can any one help?

**Comment by danirus** [comment]
It sounds as if you forgot to activate the virtualenv before installing django-comments-xtd. As you already pointed out, a directory called `django_comments_xtd` has to exist in `lib/python3.8/site-packages/`. Try to activate the virtualenv and then install the package, in that order, as stated in the [introduction](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#introduction) of the tutorial.

**Comment by dtdibaba** [comment]
Here are my codes:
source ~/Desktop/WEB2/bin/activate
pip3 install django-comments-xtd  

Feedback:
Requirement already satisfied: django-comments-xtd in ./Desktop/WEB2/lib/python3.8/site-packages/django-comments-xtd (2.8.1)

I have added:
 'django_comments',
 'django_comments_xtd',
to my INSTALLED_APPS.

And I have added:
COMMENTS_APP = "django_comments_xtd"

![Screen Shot 2020-11-21 at 10 36 54](https://user-images.githubusercontent.com/32692814/99882365-7f689e80-2be5-11eb-8e4e-a3b59f35a317.png)

The error message says: 

Request Method: | POST
-- | --
http://127.0.0.1:8000/comments/post/
django.contrib.flatpages.views.flatpage

No flatpage matches the query.

**Comment by danirus** [comment]
As the error says, you don't have a `flatpage` matching the query.
What makes you think it's an issue with django-comments-xtd?

**Comment by dtdibaba** [comment]
In the demo, I have not seen a flatepage created for the comments objects. In my app, I have a Comment model that shows comments and counts the number of comments for a post. That is too basic. It does not have a moderator functionality. All comments are free and the comments appear on the post even though I can disable or delete a comment from the admin page. It is a bare minimum one. What I am trying to do is to improve the comment system such that all comments are moderated before they appear on the post except those posted by authenticated users. 

I have a FlatePage on my admin site, do I have to create it from the admin page?
I get the basic comments on my admin dashboard because I have created a model and registered it. 
In the django_comments_xtd, case I thought the package itself handles that I have not created a Comment model for it or link with the existing one. The only model I created for the django_comment_xtd is the PostCommentModerator model.
When I run the server, it shows me:
"
?: (2_0.W001) Your URL pattern '^comments/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
?: (2_0.W001) Your URL pattern '^comments/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
"
The only place where url or re_path and (?P<', or $ is used is in the django_comments and django_comments_xtd packages. 
Do you think this is the reason? It seems django_comments_xtd does not render the preview.html and other templates. Nor does it save the comments to the database.
What should I do to get both? The error is related to that. When I fill out comments to the form rendered by my detail.html template after adding the render_comment_form and render_xtdcomment_tree tags , and hit post or preview, it raises the error as above.
I hope this helps to understand how they are linked.

**Comment by danirus** [comment]
django-comments-xtd doesn't have a requirement on the flatpages app. Here I would be glad to help you if there was a problem with django-comments-xtd. But that is not the case. To understand how to integrate the app with Django projects you could try to get acquainted with the code of the tutorial, and additionally and very valuable, playing with the demos.
Good luck.

**Comment by dtdibaba** [comment]
I understand, it is not the problem of django-comments-xtd. I assume I might have missed something.
The issue is it does not take me to the preview page or post the comment at all. So, the problem is, the django-comment-xtd  forms, models, and views are not properly working for me. It does not save the comments on the admin page under COMMENTS XTD either.   
Sorry for bothering you,and  thanks.

**Comment by danirus** [comment]
It looks like you forgot to create the template for a flatpage. The flatpages app is documented [here](https://docs.djangoproject.com/en/3.1/ref/contrib/flatpages/). 

I recommend you to slow down and enjoy learning Python/Django. Django is a large product that will save you a lot of time, code and headaches, it takes time to master it. I still don't. I find myself reading the docs very often, and I started using it before v1.0.

As for django-comments-xtd, I added 3 demo projects (in addition to the tutorial) that you can run to understand how to use it. It is in the docs, [here](https://django-comments-xtd.readthedocs.io/en/latest/example.html).

**Comment by danirus** [comment]
Don't hesitate to reopen the issue if you find out there is issue in django-comments-xtd.
