### ISSUE TITLE
Localized submit_date in JavaScript plugin

### ISSUE THREAD

**Issue by Loneattic** [danirus/django-comments-xtd#248]
How can I localize the submit_date when using the JavaScript plugin?

Plugin gets the UTC date, as specified in the Django settings. Usually the date in the template adjusts itself for each user's local time. But comments display it in UTC.

**Comment by danirus** [comment]
Thanks for this report @Loneattic. It's a good catch!

**Comment by danirus** [comment]
The fix for this issue has been released with v2.8.2.
