### ISSUE TITLE
 Submit fill out the form, send after authorization

### ISSUE THREAD

**Issue by ogurec-ogurec** [danirus/django-comments-xtd#249]
@Danirus, I have a little idea.
More than once I noticed such a thing on the sites that there is a form for sending comments, you can enter a comment in it, but when you click on the "Submit" button, a window with atorization appears. After authorization, the comment is sent.

That is, we first let the user write a comment, but he can only send it by logging in. Do you think this can increase the conversion to action?

Here's an example:

Input comment:
![image](https://user-images.githubusercontent.com/66796268/103231046-3386d480-48ca-11eb-9cb6-c35842b8dab4.png)

Window after the submit button:
![image](https://user-images.githubusercontent.com/66796268/103231278-bd36a200-48ca-11eb-82b0-aa83432bc454.png)

What do you think about this?

**Comment by danirus** [comment]
Thanks for the idea @ogurec-ogurec. 
But honestly, I don't like to fall in such tricks 😅 I prefer not do it.
