### ISSUE TITLE
Give back the maintainer right

### ISSUE THREAD

**Issue by bashu** [danirus/django-comments-xtd#25]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by bufke** [comment]
+1 would love to see a Django 1.8 release.

**Comment by danirus** [comment]
I will do it eventually. I'm sorry for the long delay. Work and parenthood are on top of this code in my priority list. However I have it planned before Summer. In the meanwhile anyone are free to fork and implement a more modern approach. I will kindly point out there if I see it as a compatible evolution.
