### ISSUE TITLE
Django-comments-xtd

### ISSUE THREAD

**Issue by odescopi** [danirus/django-comments-xtd#257]
Good day Dan..I have successfully implement the django-comments-xtd app to my project..but there is a little glitch.. after I implemented the Java script API plug in,it doesn't affect the COMMENT_XTD_MAX_THREAD_LEVEL.. because even after i set it 0 at the backend yet the frontend still carries a clickable reply link attached to the comment..and when feed in a reply the whole comment system freeze at the front end and stop rendering..

**Comment by danirus** [comment]
Duplicate #256.

**Comment by odescopi** [comment]
Good day Dan..thanks for your help..I have implemented the charges but it
seems after installing django-comments-xtd package there is only
2.8.0,2.8.1,and 3.0.0 js plugin there is no 2.8.2..after I changed the src
in the static files link in articles_detail to 2.8.2 just like u
implemented there is not comment form showing..but when I reverted back to
2.8.1 the comment form appeared but the issue still persists..

**Comment by danirus** [comment]
Hi @odescopi, I'll make a release (v2.8.2) no later than Monday that will include the fix for this issue.
Before Monday you could use the master branch and run `npm run build`. If you run the command in master it will build the plugin v2.8.2. You will have to change your templates to use that version.

**Comment by odescopi** [comment]
Thanks Dan.. please be my mentor..lol...u are really good at what u do..
thanks am grateful ..I'll wait till Monday.. PS if install the latest
version I wouldn't have to change my template much(article_detail)..just
the script Js src link(2.8.2)..

**Comment by odescopi** [comment]
Good day dan.. please my project has a user app so only authenticated users
can comment but it seems your login for unauthenticated users redirects to
to Django admin login page (reply,likes, dislikes,flag) instead of a user
login page I created..how do I reset it to my user login page..
Also it seems ur flagging doesn't render on the same page like
reply,likes..it opens another page could it be possible?

**Comment by danirus** [comment]
Hi @odescopi, please, ask this kind of questions in [Discussion](https://github.com/danirus/django-comments-xtd/discussions).
Thank you!

**Comment by odescopi** [comment]
Thanks dan..I just posted my question on the discussion platform..
