### ISSUE TITLE
Demo errors

### ISSUE THREAD

**Issue by wgoedeck** [danirus/django-comments-xtd#26]
After installing django_comments_xtd from github and running, I get the error: 
django_comments_xtd.XtdComment.comment_ptr: (fields.E300) Field defines a relation with model 'Comment', which is either not installed, or is abstract.

I don't see any problem with either my code nor the django_comments_xtd code, such as a ForeignKey error where one app needs to link to another app, e.g.: 
comment_ptr = models.ForeignKey(Comment) 
should be: 
comment_ptr = models.ForeignKey(django_comments_xtd.Comment) 

See also: 
http://stackoverflow.com/questions/29810195/fields-e300-error-with-django-threadedcomments

Thanks,
Walter Goedecke

**Comment by danirus** [comment]
Did you install [django-contrib-comments](https://github.com/django/django-contrib-comments) or are you using a version of Django that still comes with `django.contrib.comments`?

Can you import your django-contrib-comments app in the `python manage.py shell` ran inside your demo project directory? (either `import django.contrib.comments` or `import django_comments` must work).

**Comment by wgoedeck** [comment]
Thanks for your reply. I do have django-contrib-comments installed - I have tried it for a website I was developing - it is deprecated, though. I had first tried to build simple-threads from startproject, then create app with Py-Dev, but then received the "django_comments_xtd.XtdComment.comment_ptr: (fields.E300) Field defines a relation with model 'Comment', which is either not installed, or is abstract" error. 

I've now tried to run two of the three applications as directed in a virtual environment (simple, and simple threads), but received numerous errors, that I can't troubleshoot, such as: 
"Could not import settings 'simple_threads.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named simple_threads.settings"
This I can't explain, as I have the settings file copied to both the root directiory, simple_threads, and the sub-directory simple_threads that I added. Also, "from django_comments_xtd import LatestCommentFeed" comes up with a LatestCommentFeed error. 

Does the project actually run without the "simple_threads" sub-directory? Should I run the application as downloaded, without moving any components?  

You can email me off-line at walter@snowbears.org, as I'm very new to Django, and although I've overcome many new challenges, this one is becoming daunting. 

Thank you very much,
Walter

**Comment by danirus** [comment]
Hi @wgoedeck, sorry for the long delay.

I just updated the package in PyPI and in Github. To play with the demos you need the source code from GitHub (I don't distribute the demos with the PyPI package). As an extension of what I wrote [here](http://django-comments-xtd.readthedocs.org/en/latest/example.html) you would probably prefer to create a virtualenv to test the project in an isolated python environment. These are the steps I would go through to try the demos:

 * Get virtualenv, `pip install virtualenv`
 * Set up a python environment for the project, `virtualenv ~/venv/try-comments-xtd`
 * Activate it, `source ~/venv/try-comments-xtd/bin/activate`
 * Clone the repository, `git clone git://github.com/danirus/django-comments-xtd.git`
 * Install the requirements, `pip install -f requirements.pip`
 * Then go to the demo you want to try (cd `django-comments-xtd/django_comments_xtd/demos/simple), and run `sh install.sh`
 * Run the development server: `python manage.py runserver`.
 * Go to your browser and point to: `http://localhost:8000`.

Whenever you are done with the `try-comments-xtd` virtualenv you can simply delete it.
Let me know if it works for you.
