### ISSUE TITLE
Variable Wrongly Named

### ISSUE THREAD

**Issue by manisar2** [danirus/django-comments-xtd#279]
Thanks for making such an awesome, well-documented and well-supported application!

There seems to be a variable wrongly named - either it should be `dislikedit` in models.py, or `disliked` in user_feedback.html.

Currently in templates\includes\django_comments_xtd\user_feedback.html, we have:
```
    <a href="{% url 'comments-xtd-dislike' item.comment.pk %}"
       class="{% if not item.dislikedit %}mutedlink{% endif %}">
        <span class="fas fa-thumbs-down"></span></a>
```
And in models.py, there is:
```
            if with_feedback:
                flags_dict.update({
                    'likedit_users': likedit_users, 'likedit': likedit,
                    'dislikedit_users': dislikedit_users, 'disliked': dislikedit
                })
```
This means that, in user_feedback.html, the variable referred to as `item.dislikedit` always results in `False`.
Please have a look.

Also, I was not able to find a mention of these variables in documentation. `likedit_users` and `dislikedit_users` are explained, but these two variables returning `True` and `False` need to be added I think.

**Comment by danirus** [comment]
Hi @manisar2, thank you for your kind words, and for the report, it's a good catch!

**Comment by danirus** [comment]
It's already fixed. It will be part of v2.8.4. 
But I want to resolve another issue before I make the release.
Thanks again @manisar2!

**Comment by manisar2** [comment]
My pleasure, thanks for the fix!

**Comment by manisar2** [comment]
@danirus I see no change, am I missing something?
**Removal:**
 ```
                   'likedit_users': likedit_users, 'likedit': likedit,
                    'dislikedit_users': dislikedit_users, 'disliked': dislikedit
```
**Addition**
```
                    'likedit': likedit,
                    'disliked': dislikedit,
                    'likedit_users': likedit_users,
                    'dislikedit_users': dislikedit_users
```

**Comment by danirus** [comment]
You might be looking in the source code of the pip installed package.
The fix is in the master branch, [here](https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/models.py#L156) in GitHub. I have not release a new version yet.
I need to work on another issue before I prepare a new release.

However, you can install the version in GitHub. Just clone the repository, cd into it with your virtualenv enabled and run `pip install -e .`. That way you will get the latest code installed in your virtualenv.

**Comment by manisar2** [comment]
I was looking at the [change log](https://github.com/danirus/django-comments-xtd/commit/134dd64d5e750ff404f480e5d3f8c82720e2e007#diff-d7d495b4c2a42a9c801009794420b9ffaae62010fcdea454a12d4f45bf8085e9). Also looked in the [repo](https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/models.py#L156). I think you meant to change the **key** `disliked` to `dislikedit`.
Currently, there isn't anything changed as it appears to me.
![image](https://user-images.githubusercontent.com/23711188/107678991-44f92580-6c59-11eb-897c-82f6bb399942.png)

**Comment by danirus** [comment]
This happens when I pretend to fix something before I have breakfast.
Thank you again @manisar2.

**Comment by manisar2** [comment]
NP!
