### ISSUE TITLE
Double click on the button (send comment)

### ISSUE THREAD

**Issue by ogurec-ogurec** [danirus/django-comments-xtd#284]
The situation is this: If you fill out a comment and very quickly click on the "Submit" button (for example, by double clicking), then the comment is published twice - duplicated. Maybe three.This applies to comments and answers. Perhaps this already needs to be implemented on the user side (double-click protection), but I can't help but mention it.

![image](https://user-images.githubusercontent.com/66796268/107817365-5c8fe700-6d09-11eb-95aa-00df003d933f.png)

**Comment by danirus** [comment]
Thanks for the report @ogurec-ogurec. Can be fix in the frontend, disabling the send button since it's been clicked and until there is a response.
