### ISSUE TITLE
Comment tree

### ISSUE THREAD

**Issue by ShayestehHS** [danirus/django-comments-xtd#314]
Hello and thanks for your API 😅
I have a problem to comments
Reply to comments are not look as tree
They look like these:
- comment
- reply to comment
I want to look like these:
- comment
- -reply to comment
_______________________________________
I don't  know that what is the problem
{% render_xtdcomment_tree for blog %} => this code used in html
[
![Untitled](https://user-images.githubusercontent.com/73740182/121671707-25b5bc00-cac4-11eb-8dd0-a97dc9feb17a.png)
](url)

**Comment by danirus** [comment]
Hi @ShayestehHS, sorry for the late answer.
It looks like you are not adding the .css file. I failed to mention it in the tutorial.
Check your templates to see if you have this:

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

**Comment by ShayestehHS** [comment]
NO😢😔😔

**Comment by danirus** [comment]
One question, what it is `blog` in `{% render_xtdcomment_tree for blog %}`?

With the information that you posted here it's difficult to say anything other than it certainly looks like it is missing the bootstrap CSS file. Can you post the output of the console of your browser?

Also, did you go through the complete [tutorial](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html)?

**Comment by ShayestehHS** [comment]
I am really really really sorry because of taking your time
You are right
Problem solved after add cdn of bootstrap
I should update my bootstrap 😔🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by danirus** [comment]
My pleasure ;-)
