### ISSUE TITLE
1064 SQL syntax error

### ISSUE THREAD

**Issue by abiatarfestus** [danirus/django-comments-xtd#318]
Hi Danirus! I'm trying to implement django-comments-xtd on my blog for the first time. Almost everything seems to be well, except that I'm getting this error when posting (authenticated user) or confirming (anonymous user) comments:
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY `django_comments_xtd_xtdcomment`.`thread_id` ASC, `django_comments_x...' at line 1")

Any advice on how to resolve it? I'm using MySQL DB.

**Comment by abiatarfestus** [comment]
Resolved it by downgrading Django from 3.2 to 3.1

**Comment by ironworld** [comment]
Hi Guys!

This error occurs on MySQL 8.0.25. To my case, the exception is launched after call function `def publish_or_unpublish_nested_comments(comment, are_public=False):`, on line `s.update(is_public=are_public)`. 

What I did to avoid this problem, I'm executing the update only if `qs` variable is valid:

`def publish_or_unpublish_nested_comments(comment, are_public=False):
    qs = get_model().objects.filter(~Q(pk=comment.id), parent_id=comment.id)
    nested = [cm.id for cm in qs]
    if qs:
        qs.update(is_public=are_public)
    while len(nested):
        cm_id = nested.pop()
        qs = XtdComment.objects.filter(~Q(pk=cm_id), parent_id=cm_id)
        nested.extend([cm.id for cm in qs])
        if qs:
            qs.update(is_public=are_public)`


Thanks!

**Comment by danirus** [comment]
Thank you all for helping with this issue, and for your patience :-)
It's been merged in 2.9.3 and released already.
