### ISSUE TITLE
Installation from repository with pip installs older version

### ISSUE THREAD

**Issue by PetrDlouhy** [danirus/django-comments-xtd#337]
I am trying to install the project with:
```
pip install git+https://github.com/danirus/django-comments-xtd#egg=django-comments-xtd
```

But it ends up installing older versions of PyPI packages: `django-comments-xtd-2.3.1`, `Django-2.2.24` and old DRF.

This is really veird behavior - seems like it has `django-comments-xtd` dependency on itself. I am trying to figure out what is really happening.
One problem, that I found is the old version `2.3.1` set in header of `pyproject.toml` file. But I don't know why is this taken as a dependency.

**Comment by danirus** [comment]
Yes, the pyproject.toml file is outdated.
Another developer kindly added it and I forgot to update it since then.

**Comment by PetrDlouhy** [comment]
I don't think, that the outdated pyproject.toml is the only problem. I had to erase it completely, because otherwise PIP would install the current PyPI version of `django-comments-xtd`, but I wanted to install from repository with my changes.
I don't know, why PIP does that, but it is very confusing.

**Comment by danirus** [comment]
26d1d9f05c443446cdb001169865424189996f49 resolves this issue.

**Comment by danirus** [comment]
This was fixed more than six months ago... If it happens again, please, don't hesitate to reopen.
