### ISSUE TITLE
Follow-up email notifications to object authors

### ISSUE THREAD

**Issue by jdbit** [danirus/django-comments-xtd#340]
Hi,
I added comments to an object (post) created by a user. Is there a way to send follow-up notifications about new comments to the user who created this post? Probably I can do this through signals, but just curious if it has been already implemented in django-comments-xtd.

**Comment by danirus** [comment]
Hi @jdbit, I am afraid not, it's not implemented.

I would do it connecting to `comment_was_posted`, and I would verify that the email address of the user that posted the object is not among the email addresses of the users that already have sent comments, to avoid sending more than one email to the same email address.

 It would be a nice feature addition.

**Comment by jdbit** [comment]
I'll do it through signals then. Thank you!
