### ISSUE TITLE
"dislike" a comment not working properly, caused by a small error in dislike.html

### ISSUE THREAD

**Issue by simonjoeca** [danirus/django-comments-xtd#358]
Issue: "dislike" a comment not working properly, such as comments/dislike/2/, it asks to fill the next form, which I happen to have one, on the same page as well.

Cause: in django_comments_xtd/dislike.html, the `<form>` missing a matching `</form>`, so it process everything till the next `</form>`

Solution: Just add the matching `</form>` in django_comments_xtd/dislike.html

**Comment by danirus** [comment]
Thanks @simonjoeca. You found it and provided the solution, that's almost it. 
It would simply be perfect if you could send a PR to fix it. 
Please, let me know. Otherwise I'll do it.
