### ISSUE TITLE
Add option to set email from address

### ISSUE THREAD

**Issue by ppershing** [danirus/django-comments-xtd#37]
Right now django-comments-xtd uses ```settings.DEFAULT_FROM_EMAIL```. It would be nice if this is somehow customizable.

**Comment by danirus** [comment]
I'll do it.
It will be available in the next release, which I hope it will be ready before the end of the month.

**Comment by danirus** [comment]
@ppershing, sorry for the long delay...
You can now use ``COMMENTS_XTD_FROM_EMAIL`` instead of ``DEFAULT_FROM_EMAIL``. It will default to the latter in case you don't define any value in your settings module.
