### ISSUE TITLE
any chance of a release with django-contrib-comments 2.2.0 ?

### ISSUE THREAD

**Issue by minusf** [danirus/django-comments-xtd#370]
2.2.0 has fixed some important validation issues:

https://github.com/django/django-contrib-comments/commit/4da9d1f85bd02b701d644e5f7fc689350c28dc68

**Comment by danirus** [comment]
Yes, @minusf.
I will do a release.
Thanks for the reminder.

**Comment by danirus** [comment]
Fixed with c5bb7a9.
Release 2.9.6 is already pushed to PyPI.
