### ISSUE TITLE
Did anyone tested with Django 4.0 and python 3.10.5

### ISSUE THREAD

**Issue by engrimran7** [danirus/django-comments-xtd#375]
Hi All please confirm if anyone has tested Django Comments Xtd with django 4.0 and python 3.10

**Comment by danirus** [comment]
I did some months ago. But the master branch doesn't have the changes yet.
I will update it.

**Comment by danirus** [comment]
I double checked today, and it works without problem with Django 4.
Only the battery of tests is not configured yet to run in Django with Python 3.10. I have checked and they pass. 

So yes, you can use django-comments-xtd with Django 4.

**Comment by JanMalte** [comment]
Checks for django 4.0 and 4.1 going to be added by #380 
As soon as this is merged, adding python 3.9 and 3.10 could be added as well.

**Comment by JanMalte** [comment]
Python 3.10 is tested now. This issue can be closed.
