### ISSUE TITLE
Support Django Rest Framework 3.14.0

### ISSUE THREAD

**Issue by aliceni81** [danirus/django-comments-xtd#389]
After I upgrade django from 4.0 to 4.1, an error occurs
**ValueError: The file 'rest_framework/css/bootstrap-theme.min.css.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fe2279385e0>.**

The latest version of django rest framework is 3.14.0 supporting django 4.1(https://www.django-rest-framework.org/community/release-notes/#314x-series), however the current package only supports the version lower than 3.14.

If I manually install djangorestframework 3.14.0, the following error shows
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
django-comments-xtd 2.9.8 requires djangorestframework<3.14,>=3.12, but you have djangorestframework 3.14.0 which is incompatible.**

**Comment by danirus** [comment]
Thanks for telling :-)

**Comment by aliceni81** [comment]
@danirus Thanks a lot for your quick handling.

**Comment by cfdbwrbq** [comment]
Hi, @danirus, thanks for the app. How about drf 3.17.1? The breaking changes from 3.16.1 aren't as bad. I think so. Thanks!
