### ISSUE TITLE
Way to take email address from User model

### ISSUE THREAD

**Issue by honzahosek** [danirus/django-comments-xtd#40]
Is there a way to ask name and email only from anonymous user? If we already have confirmed email we should not ask for it again. I did not find easy way to make request.user accessible from the form or use different form for logged in users.

**Comment by danirus** [comment]
Hi @honzahosek, sorry for the long delay. Too busy with other projects.
I'll document the case you propose, hopefully before the end of month.

**Comment by danirus** [comment]
Did you try to enclose the `name`, `email` and `url` form fields in a `{% if not user.authenticated %}...{% endif %}` condition, in the `form.html` template? 

That way, if the user is authenticated, they won't be presented to the user. When those fields are empty but the user is authenticated django-contrib-comments fills them up with the name and email of the user active in the request.
