### ISSUE TITLE
Make comment model manager API consistent with django-contrib-comments

### ISSUE THREAD

**Issue by zmrenwu** [danirus/django-comments-xtd#41]
In django-comments-xtd, `XtdComment` reimpliments the model manager that inherit from `models.Manager`. It have only one API: `for_app_models`. This is not consistent with django-contrib-comments model manager API which contains two API:  `in_moderation` and `for_model`. So it's hard to plugin the app to some project which using some django-contrib-comments API. That what I get in trouble. I have no idea how to custom it instead of change the source code.
So why the model manager not inherit from django-contrib-comments model manager that make the app more compatible?

**Comment by danirus** [comment]
@zmrenwu, thank you for your report. It's been resolved and fixed.
