### ISSUE TITLE
broken link on documentation page

### ISSUE THREAD

**Issue by ProTankerAlfa** [danirus/django-comments-xtd#428]
The link below (also shown in the image) of the this [documentation page](https://django-comments-xtd.readthedocs.io/en/latest/quickstart.html)  gives error 404:
![image](https://github.com/user-attachments/assets/c700f304-5e49-4584-a858-08e91d2fb711)

wrong link: https://docs.djangoproject.com/en/5.0/_objects/ref/contrib/sites/#enabling-the-sites-framework

correct link: https://docs.djangoproject.com/en/5.0/ref/contrib/sites/#enabling-the-sites-framework

or dev version: https://docs.djangoproject.com/en/dev/ref/contrib/sites/#enabling-the-sites-framework

**Comment by ProTankerAlfa** [comment]
other links that point to the django page seem to have the same problem

**Comment by danirus** [comment]
The links are fed automatically with the Django inventory of Sphinx objects, [here](https://github.com/danirus/django-comments-xtd/blob/master/docs/conf.py#L243).
I will take a look. Thanks for telling.
