### ISSUE TITLE
Not working with Wagtail - 'NoneType' object has no attribute 'must_be_first'

### ISSUE THREAD

**Issue by songproducer** [danirus/django-comments-xtd#432]
Hello, after somehow initially getting django-comments-xtd working with wagtail, I've been trying for days to get it back to working but I'm not sure what broke it.

I just cloned the [Wagtail bakery demo](https://github.com/wagtail/bakerydemo) and reproduced the issue.

Putting this in any template file causes the error:
```
{% extends "base.html" %}
{% load wagtailimages_tags comments_xtd comments %}

{% render_comment_form for page allow_feedback show_feedback %}
```

**Comment by danirus** [comment]
Hi @songproducer, I will be glad to help you if you put the code in a repository.

**Comment by songproducer** [comment]
Hi @danirus thanks very much!

It seems I did not have the virtual environment installed. I installed it and it's working now!

**Comment by danirus** [comment]
That happens to me all the time. Cheers!
