### ISSUE TITLE
Migrating old django_comments to django_comments_xtd data

### ISSUE THREAD

**Issue by asgaines** [danirus/django-comments-xtd#44]
Hello! I'm loving this project so far. It has thus far been very easy to switch to the valuable extensions provided by this project. However, I'm struggling with migrating my old comment data (from `django_comments`) to the new format. Am I missing a command or method which would make this simple?

**Comment by danirus** [comment]
I'm sorry @asgaines I missed your question. That would be indeed a good addition. 
I guess you already resolved it. Nevertheless it's worth adding a command to help with it.
Thank you for your report.

**Comment by danirus** [comment]
@asgaines, a new command **populate_xtdcomments** provides this feature. It's been implemented in b0cc5b439fc006102141f800545a80041a2e6cd5 and released with v2. Check out [this page](http://django-comments-xtd.readthedocs.io/en/latest/migrating.html) in the documentation. Thanks for your report.
