### ISSUE TITLE
'OrderedDict' object has no attribute 'move_to_end'

### ISSUE THREAD

**Issue by KhanMaytok** [danirus/django-comments-xtd#45]
I'm with Python 2.7.13. I try to replicate the Tutorial, but when I create the form.py I have an error in this line:

     self.fields.move_to_end('comment', last=False)

The error is `'OrderedDict' object has no attribute 'move_to_end'` I read the error is at Python 2.6, but I have Python 2.7. I don't understand the error...

**Comment by asgaines** [comment]
Yes, I remember the tutorial having a number of issues myself. It is not updated sufficiently to be in keeping with the code in this repo.

**Comment by danirus** [comment]
Indeed, `move_to_end` was added in Python 3, so if you are using Python 2.7 that piece of the tutorial doesn't work. Python 2.7 is going to be around for quite sometime so I understand your complain when I focused only in Python 3.

The `move_to_end` in the tutorial is not mandatory, it's just to move the `comment` field to the first position of the form. You could rearrange the position of the `comment` field in Python 2.7 replacing the `move_to_end` for something like:

    self.fields = OrderedDict([('comment', self.fields['comment'])] + 
                              [field for field in self.fields.items()])

Add `from collections import OrderedDict` the top of your module. That should make it.

**Comment by KhanMaytok** [comment]
Yes, I only comment this line and works. Many thanks, problem done
