### ISSUE TITLE
Changing COMMENTS_XTD_LIST_ORDER results into django complaining about missing migration

### ISSUE THREAD

**Issue by barsch** [danirus/django-comments-xtd#48]
```
class XtdComment(Comment):
    ...

    class Meta:
        ordering = settings.COMMENTS_XTD_LIST_ORDER
````

any change in the Meta class will result into a new migration once you run ```python manage.py makemigrations``` - the ordering should be changed in ```XtdCommentManager.get_queryset``` instead

Django==1.10.5
django-comments-xtd==1.6.5

**Comment by danirus** [comment]
Hi @barsch, thank you for the catch.
