### ISSUE TITLE
Please add select_related to XtdCommentManager.get_queryset to reduce number of queries

### ISSUE THREAD

**Issue by barsch** [danirus/django-comments-xtd#49]
I use the following monkey patch to speed up things on my page (reduce the number of queries) - would be nice if this could be added directly into master - but fine with me if not

```
from django_comments_xtd.models import XtdCommentManager

# select_related on comments to speed up things
def get_queryset(self):
    qs = super(XtdCommentManager, self).get_queryset()
    return qs.\
        select_related('user', 'content_type').\
        order_by('-submit_date')
XtdCommentManager.get_queryset = get_queryset
```

PS: here you could als add the order settings mentioned in #48

**Comment by danirus** [comment]
Yes @barsch, I like it very much. I'm fixing #48 and pushing it to master in 1.6.6.
Thanks for the fix and the enhancement.
