### ISSUE TITLE
templates bug

### ISSUE THREAD

**Issue by Wladislav** [danirus/django-comments-xtd#50]
Good day! 
django-comments-xtd/django_comments_xtd/templates/django_comments_xtd/reply.html
Need add {% block content %}

**Comment by danirus** [comment]
Hi @Wladislav, the `reply.html` template is just a boilerplate template, it's not meant to be used right away. If you need it inside a `{% block content %}` you must override it by including your customized `reply.html` template in your Django project template's directory. 

If you use a `TEMPLATES` settings like this:

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, "templates"),],
            'APP_DIRS': True,
        }
    ]

Your project template's directory (the one listed above, within `DIRS`) will take precedence over the templates directory provided by django_comments_xtd or any other app. Create a `django_comments_xtd` directory in your project template's directory, add add your customized `reply.html` template in there.
