### ISSUE TITLE
Comment confirmation url can generate invalid url

### ISSUE THREAD

**Issue by Naddiseo** [danirus/django-comments-xtd#51]
The url generated for confirming comments can exceed the 4096 character limit even if the comment itself is a single character. This is due to what data gets pickled in the url generation process.

I've tracked down the issue to [the `XtdCommentForm.get_comment_create_data`](https://github.com/danirus/django-comments-xtd/blob/e6b8cf1657ec04a0025c2b0b8c9f184612a419fd/django_comments_xtd/forms.py#L51-L55) which inserts the full `content_object` into the `TmpXtdComment` object which is to be pickled. The problem is that the `content_object` (in my case) is for a blog post which has a content length near to the 4k limit, thus when the comment is pickled and base64 encoded, the eventual url is greater than 4k characters.

It might be able to be fixed by removing the `content_object` from the `TmpXtdComment`, then load it manually once verified.

**Comment by lgellert** [comment]
Ran into this too.  TmpXtdComment is not stored anywhere in the database, the comment only lives on the encoded URL. I wound up creating a temp table to store the anonymous comment data with a unique id for the token and passed that in the email.

**Comment by danirus** [comment]
Thanks @Naddiseo and @lgellert for the comment.
It surprises me that this bug has been there unnoticed for such a long time.

Looking into your PR, @Naddiseo, I would leave the `views.py` module as it is, and rather fix the `TmpXtdComment`, removing `__reduce__` and adding both `__getstate__` (to delete attribute `content_object`) and `__setstate__` (to reestablish `content_object` out of the `content_type` and `object_id`). If you don't have time to fix it I'll do it as soon as I get 5 minutes.

Thanks again for the catch!
