### ISSUE TITLE
Associate comments with an already authorized user.

### ISSUE THREAD

**Issue by NogerbekNurzhan** [danirus/django-comments-xtd#54]
**Thanks for this project!**

I have little question. I successfully added this app to my project and use `{% render_comment_form for object %}` in template. Is shows me fields like "Name", "Email", "Url" and "Comment".

Question: Is it possible to show only "Сomment" field and associate these comments with an already authorized user. What I need to customize? I am little bit comfused.

**Comment by danirus** [comment]
Hi @NogerbekNurzhan. Yes, it's possible. 
In the templates directory in your project, create a `comments` directory and copy in there the `form.html` file you use to render your comments form. Then edit it, and wrap the fields you don't want to show when the user is authenticated within an if-endif clause, like the following:

    {% if not request.user.is_authenticated %}
    <div class="form-group {% if 'name' in form.errors %}has-error{% endif %}">
      <label for="id_name" class="control-label col-lg-3 col-md-3">
        {{ form.name.label }}
      </label>
      <div class="col-lg-7 col-md-7">
        {{ form.name }}
      </div>
    </div>

    <div class="form-group {% if 'email' in form.errors %}has-error{% endif %}">
      <label for="id_email" class="control-label col-lg-3 col-md-3">
        {{ form.email.label }}
      </label>
      <div class="col-lg-7 col-md-7">
        {{ form.email }}
        <span class="help-block">{{ form.email.help_text }}</span>
      </div>
    </div>

    <div class="form-group {% if 'url' in form.errors %}has-error{% endif %}">
      <label for="id_url" class="control-label col-lg-3 col-md-3">
        {{ form.url.label }}
      </label>
      <div class="col-lg-7 col-md-7">
        {{ form.url }}
      </div>
    </div>
    {% endif %}

That code excerpt comes from the tutorial, only the wrapping `{% if not ... %} ... {% endif %}` is new. If the user is authenticated those fields are not necessary, the default behaviour is to extract them from the authenticated user when not provided in the form.

**Comment by NogerbekNurzhan** [comment]
Thanks!
