### ISSUE TITLE
Want to exclude Title and URL fields from comment form. How to do this?

### ISSUE THREAD

**Issue by ZaibiMughal** [danirus/django-comments-xtd#56]
Hey i have been working on your pakcage for the last 4-5 days. Actually i am new to django and i am not getting it how to remove the fields from the form. Can you please help me out!

**Comment by danirus** [comment]
Hi @ZaibiMughal,
Have you read the [tutorial](http://django-comments-xtd.readthedocs.io/en/latest/tutorial.html)?

**Comment by ZaibiMughal** [comment]
Yes i have,. But unable to find the right solution. May be i am not getting it all :(

**Comment by danirus** [comment]
There's no `title` field in the comment form. 
The `url` is optional, so you can override the template and get rid of it.

If you are new to Django, follow the [tutorial](https://docs.djangoproject.com/en/1.11/intro/). It is very well documented. Also there are good books about Python and Django that you can read to develop your confidence. Be patient and enjoy the reading.

**Comment by ZaibiMughal** [comment]
OK thanks alot! i will follow the tutorial right now!
