### ISSUE TITLE
object don't have get_absolute_url method

### ISSUE THREAD

**Issue by ZaibiMughal** [danirus/django-comments-xtd#57]
I have implemented the commenting package into my template. Everything is working fine except when i press the send buttin it goes to a page and shows this (see Screenshot) http://prntscr.com/f2mjbl, but when I goes back to my commenting page and refresh it then the comment is there. I want to redirect to the same page when i click on send button. Please help me i have a project to complete asap. Thanks

**Comment by ZaibiMughal** [comment]
This was the first error that i got. Then i implemented the reverse function then the error that i got is in my first message!

**Comment by danirus** [comment]
The object's model to which you are posting comments requires the method `get_absolute_url`. See the `Article` model [in the simple example project](https://github.com/danirus/django-comments-xtd/blob/master/example/simple/articles/models.py). Your Album model has to implement such method too. Read about it [in the official Django documentation](https://docs.djangoproject.com/en/1.11/ref/models/instances/#get-absolute-url).
