### ISSUE TITLE
Missing staticfiles?

### ISSUE THREAD

**Issue by Alexeyisme** [danirus/django-comments-xtd#58]
After installing `pip install django-comments-xtd==1.7.1` django_comments_xtd folder doesn't have any static in it.

Pythonanywhere error log:
`ValueError: Missing staticfiles manifest entry for 'django_comments_xtd/css/bootstrap.min.css'`

Not sure it's an issue. Maybe I have to set the staticfiles somehow.

It works in DEBUG = True mode without styling.

**Comment by danirus** [comment]
Thanks for telling @Alexeyisme.
I just uploaded a new version (1.7.2) to include the missing static directory.

**Comment by Alexeyisme** [comment]
Thank you! Works just great!
