### ISSUE TITLE
TypeError: <django.utils.functional.__proxy__ object at ...> is not JSON serializable

### ISSUE THREAD

**Issue by engineervix** [danirus/django-comments-xtd#62]
The above exception is thrown when sending emails using [Sparkpost's Django Email Backend](https://python-sparkpost.readthedocs.io/en/latest/django/backend.html). From the traceback, all errors point to the [django-comments-xtd/django_comments_xtd/views.py](https://raw.githubusercontent.com/danirus/django-comments-xtd/master/django_comments_xtd/views.py) and have everything to do with [translation](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.translation.ugettext_lazy). The lines are:

`subject = _("comment confirmation request")`  (line 47)
`subject = _("new comment posted")` (line 208)

My temporary workaround was to [remove the translation altogether](https://github.com/engineervix/django-comments-xtd/commit/41f33b5f8df2ce2d84a91b948b67c19b7d3048b0), and the problem was gone!

How can we ensure that the above exception isn't thrown while maintaining the translation?

Thanks

**Comment by danirus** [comment]
Would you be so kind as to post the steps to reproduce the error?
