### ISSUE TITLE
DRF Requires CommentCreate view to define a queryset

### ISSUE THREAD

**Issue by zbyte64** [danirus/django-comments-xtd#64]
Looks like a permission check is done automatically and so a queryset needs to be defined:

```
 if not permission.has_permission(request, self):
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/permissions.py", line 124, in has_permission
web_1     |     queryset = view.get_queryset()
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 68, in get_queryset
web_1     |     % self.__class__.__name__
web_1     | AssertionError: 'CommentCreate' should either include a `queryset` attribute, or override the `get_queryset()` method.
```

DRF == 3.6.3
xtd == 2.0.3
django==1.10.6

**Comment by danirus** [comment]
Could you post the complete stack? Including django-comments-xtd modules.

**Comment by danirus** [comment]
I can't reproduce this bug.
Just uploaded a Docker image to run the demo project.
https://hub.docker.com/r/danirus/django-comments-xtd-demo/
Feel free to reopen the bug if still persists, and include steps to reproduce it.
