### ISSUE TITLE
CSRF verification failed. Request canceled.

### ISSUE THREAD

**Issue by trDjango** [danirus/django-comments-xtd#65]
When I click on the send and write comment, I get 403 forbidden warning.what should I do?("POST /comments/post/ HTTP/1.1" 403 2514)

**Comment by danirus** [comment]
Are you using django-comments-xtd? Did you follow the tutorial? Are you using the JavaScript plugin or the backend alone?

**Comment by trDjango** [comment]
Hi danirus, my settings are like this;
settings.py file for django_comments_xtd;
```
INSTALLED_APPS = ['django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_comments_xtd',
    'django_comments',
    'profil',
]
SITE_ID = 1
# Either enable sending mail messages to the console:
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Or set up the EMAIL_* settings so that Django can send emails:
EMAIL_HOST = "smtp.mail.com"
EMAIL_PORT = "587"
EMAIL_HOST_USER = "alias@mail.com"
EMAIL_HOST_PASSWORD = "yourpassword"
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "Helpdesk <helpdesk@yourdomain>"

COMMENTS_APP = 'django_comments_xtd'#burası comment başlangıç
COMMENTS_XTD_MAX_THREAD_LEVEL = 2
COMMENTS_XTD_LIST_ORDER = ('-thread_id', 'order')  # default is ('thread_id', 'order')

#  To help obfuscating comments before they are sent for confirmation.
COMMENTS_XTD_SALT = (b"Timendi causa est nescire. "
                     b"Aequam memento rebus in arduis servare mentem.")

# Source mail address used for notifications.
COMMENTS_XTD_FROM_EMAIL = "noreply@example.com"

# Contact mail address to show in messages.
COMMENTS_XTD_CONTACT_EMAIL = "helpdesk@example.com"
COMMENTS_XTD_CONFIRM_MAIL = False
```

urls.py for django_comments_xtd;
`urlpatterns = [url(r'^comments/', include('django_comments_xtd.urls')),]`

template for django_comments_xtd;
```
{% extends "base.html" %}
{% load comments %}
{% load comments_xtd %}
{% load static %}
{% block content %}
{% for form in profile %} #profile = my models's name
    {% render_comment_form for form %} #
{% endfor %}
{% endblock %}
```

I get an error when I click on the submit button.
I only included the settings I made for django_comments_xtd.Thank you very much for your help.

**Comment by tahirawan4** [comment]
Any updates on above?

**Comment by danirus** [comment]
I don't know, it could be many things. Did you follow the tutorial first? If so, what are the differences with your project? That may throw some light on the issue. One thing that looks bad is the iteration in the template: 

    {% for form in profile %}
        {% render_comment_form for form %}
    {% endfor %}

What is that? A custom formset? If there's more than one instance there are more than one csrf token, what would justify the error.
