### ISSUE TITLE
Size of the JS bundles

### ISSUE THREAD

**Issue by bgelineau** [danirus/django-comments-xtd#66]
Hi, I've noticed while installing the latest version that the package size on pypi has jumped. That's due to all the JS bundles being bigger since the 2.0.3 release, especially the vendor file going from 1Mo to 2.8Mo. I don't know the reason, as I'm unable to reproduce the issue on my computer. 3Mo is big for a production environment, could you fix the problem?

Besides, would it be possible for you to build the bundles with ``webpack -p`` when releasing ? It will optimize the bundles for production (and limit the size of the pypi package).

**Comment by danirus** [comment]
Sorry for this. I'll fix it within minutes.

**Comment by danirus** [comment]
Fixed in ece8125.
