### ISSUE TITLE
Comments not deleting when object is deleted

### ISSUE THREAD

**Issue by cpkthompson** [danirus/django-comments-xtd#68]
When render comment form and render comment tree are bound to an object, say a blog post, comments don't delete when the blog post is deleted so what happens is that when a new blog posts that has the same id/pk is created, old comments re-surface and are bound this new object.

**Comment by danirus** [comment]
You have to do that in your project. Link a receiver function to the post_delete signal and delete the comments that are attached to the instance received.

**Comment by cpkthompson** [comment]
Created new app '**Discussion**'

**In settings:**

COMMENTS_XTD_MODEL = 'discussion.models.Discussion'

**In models:**
from django.db.models.signals import post_delete
from django.dispatch import receiver
from .models import Discussion

@receiver(post_delete, sender=BlogPost)
def comment_delete(instance, **kwargs):
    Discussion.objects.filter(object_pk=instance.pk).delete()
