### ISSUE TITLE
Support for passing in site via request.site (CurrentSiteMiddleware)

### ISSUE THREAD

**Issue by tony** [danirus/django-comments-xtd#69]
https://github.com/django/django/blob/7724879b524711d61b7491a4a9c104d9cff2e1e3/django/contrib/sites/middleware.py#L12

I think this may have intended to be implemented: https://github.com/danirus/django-comments-xtd/blob/b0cc5b439fc006102141f800545a80041a2e6cd5/django_comments_xtd/forms.py#L51

White the ``site_id`` didn't end up being used inside the function, I think the intention may have been to pass it in, if it existed. I think this is the desirable behavior to default to.

With this middleware, the site can be passed in through the view/request and passed to the model. This works around requiring ``settings.SITE_ID``.

**Comment by danirus** [comment]
Thanks @tony, indeed, it's a bug.
I'll fix it later today.

**Comment by danirus** [comment]
Fixed in 9046664935ef61d8c22c9d6b4dec1246e12f0ca9.
