### ISSUE TITLE
Dynamically associate CommentBox with different comments

### ISSUE THREAD

**Issue by alexcwatt** [danirus/django-comments-xtd#70]
I am working on integrating this project with a one-page app that associates comments with multiple resources, one at a time. As far as I can tell, I cannot easily change the comments associated with the `#comments` div. However, I think it would be a useful feature for this library and is one I'd like to implement.

As I don't have much experience with React, I'm wondering what the best way to go about this would be?
 Would it make sense to have an event on the div that would change the comments associated? Or perhaps there is already a way to do this?

**Comment by danirus** [comment]
The `#comments` div is just the hook upon which the React component is mounted. It's passed in the `index.js`. Just change it to specify yours, but the list of comments rendered belong to one and only one object, and that's reflected when you post new comments.

Look at the `templatetags/comments_xtd.py`module, the `get_commentbox_props` passes a `form` object to the React component to define the object subject of the comments, it's relevant to submit new comments.

I hope that helps, I'm not sure about what you want to achieve.

**Comment by alexcwatt** [comment]
Thanks @danirus. I understand that part pretty well. The problem is that I want to have multiple sets of comments on the same page: when a user clicks on a particular tab, I want to reload the comments section with a different set of comments. The difficulty is that merely changing the global comment property to which the object was initially bound does not cause the comments to reload. Does that make sense? I am looking for a solution to this. I suppose the other way to fix it would be to attach comments to different div's and hide some of them, but I'd rather only load one set at a time.

**Comment by danirus** [comment]
Alex, the code doesn't support changing dynamically (through JavaScript) the object to which the comments are attached. That's happens in the templatetag `get_commentbox_props` (sorry, I just realised, it's undocumented), which takes only one argument, the object itself to which we sent the comments.

**Comment by alexcwatt** [comment]
Okay, thank you for looking into this. Originally I was going to look at adding this but have decided for now to roll my own commenting system, as I needed to change some other things anyway. This library is awesome though!

**Comment by danirus** [comment]
Thanks @alexcwatt. Good luck and happy coding!
