### ISSUE TITLE
COMMENTS_XTD_APP_MODEL_OPTIONS

### ISSUE THREAD

**Issue by evilplanet** [danirus/django-comments-xtd#72]
Hello!

Somehow I'm not able to get flagging and feedback to work. I have a different project layout wherein my app labels also contain the project name as below:

```
class BlogConfig(AppConfig):
    name = 'projectname.blog'
    verbose_name = "Blog"
```

In the `INSTALLED_APPS` list, this is also listed as `'projectname.blog'`. 

And I have a model named Post in the blog app models.py, so how do I set `COMMENTS_XTD_APP_MODEL_OPTIONS` in this case? I've tried `'projectname.blog.post'`, `'projectname.blog.Post'`, `'blog.post'`, `'Blog.Post'`, `'blog.Post'`... No luck.

Is it possible to override the default COMMENTS_XTD_APP_MODEL_OPTIONS? For example, 
```
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    'default': {
        'allow_flagging': True,
        'allow_feedback': True,
        'show_feedback': True,
    }
}
```

Thank you!

**Comment by kkomninos** [comment]
You can try using {% render_xtdcomment_tree for object allow_feedback show_feedback allow_flagging %} in template.

**Comment by evilplanet** [comment]
@kkomninos I know. I tried. It doesn't work. I think the problem is that I have to enable that in the settings, but I don't know how to do that since my app name has a dot in it as described above. Is there a way to override the default COMMENTS_XTD_APP_MODEL_OPTIONS? Thanks!

**Comment by danirus** [comment]
Sorry for the long delay @evilplanet and @kkomninos.
It should work by adding:

    COMMENTS_XTD_APP_MODEL_OPTIONS = {
        'blog.post': {
            'allow_flagging': True
        }
    }

It's covered in the [commenting options](http://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#commenting-options) section of the tutorial. If you didn't fix it already, could you, please, try and let me know?

**Comment by evilplanet** [comment]
@danirus Thank you for your reply. I read your tutorials. It doesn't work for my case probably for the reasons described above.

**Comment by danirus** [comment]
Take a look at commit 86343a216565f54e0e7cbf761233449bf7552870, I have changed the `comp` demo site to illustrate your setup. Pull the changes from master and give it try. Your particular case can't be too far from it. Let me know.

**Comment by evilplanet** [comment]
Hey @danirus Thanks for the reply. It still doesn't work. A 404 response with the following message: `Comments posted to instances of 'blog.post' are not explicitly allowed to receive 'liked it' flags. Check the COMMENTS_XTD_APP_MODEL_OPTIONS setting.` Although in settings I have the standard configuration as below:
```
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    'blog.post': {
        'allow_flagging': True,
        'allow_feedback': True,
        'show_feedback': False,
    }
```
}

Is there a way to override the default projectwide? That would be much easier. If it helps, I'm on a Cookiecutter-Django layout.

**Comment by danirus** [comment]
The key you have to use in `COMMENTS_XTD_APP_MODEL_OPTIONS` is the `app_label.model` as registered in the ContentType table. Take a look at how your `blog.post` is registered and used that instead. It might be different than `blog.post`, reason why `django_comments_xtd.utils.has_app_model_option` fails:

    from django.contrib.contenttype.models import ContentType
    for ct in ContentType.objects.all():
        print("%s.%s" % (ct.app_label, ct.model))

**Comment by evilplanet** [comment]
I just tried your command. It prints `blog.post`. I must have done something wrong somewhere else.

**Comment by evilplanet** [comment]
Is there a way to override the default for the whole project?

**Comment by danirus** [comment]
Clone the project and replace the body of the function `has_app_model_option` with: `return True`.
That's all you need.

**Comment by evilplanet** [comment]
@danirus Thank you! I'll give it shot and let you know.
