### ISSUE TITLE
Preview loop if logged in

### ISSUE THREAD

**Issue by joyider** [danirus/django-comments-xtd#76]
Hi!

I've encountered an annoyance  regarding posting comments when being logged in:

When logged in posting a comment takes me directly to the preview screen

![alt text](https://puu.sh/xSCpW.png)

this is where I'm stuck. Reading the documentation this behavior is expected if the form has errors. But what would be classified as an error?

Posting comments not logged in and posting the URL from the terminal works, so does pure django_comments style commenting.

Under what circumstances can this be expected behavior?

**Comment by joyider** [comment]
Ok by not being so sleepy. I have this issue sort of resolved.

This is not an issue with the Django_Comment_Xtd or the underlying Djando_Comments.

By reading the content the variables(preview and form.errors) that are responsible of rendering the preview page. You can see:

`preview=False`

BUT

`form.errors` is:
`<ul class="errorlist"><li>email<ul class="errorlist"><li>This field is required.</li></ul></li></ul>`

**Email field is required and was missing in my case (test scenario and using dummy admin user)**

In production this will most likely not be an issue, since users should be created with an email. But after reading the closed issues I noticed that there were some other users reporting the same thing.

A note in the documentation might be good thing. Since the behavior in django_comment_xtd differ from core django_comments that forces you to set an email (by a simple tesdt using default settings in django_comments)
![emailforced](https://puu.sh/xTfum.png)

**Comment by danirus** [comment]
Hi @joyider, thanks for bringing this up. I'll review the documentation. It's written in many places that django-comments-xtd extends django-comments, and I presumed that's enough, but a bit more clarification wouldn't harm. I put it in my todo list.

**Comment by danirus** [comment]
For the record, 
I realized it's an actual error when used in combination with the ReactJS plugin.

**Comment by danirus** [comment]
This bug has been fixed, I still have to update the documentation so I'll leave it open until then.
