### ISSUE TITLE
Problem of mixed content on a site with the HTTPS

### ISSUE THREAD

**Issue by pamost** [danirus/django-comments-xtd#77]
Hello,
when working with a package on a site with the HTTPS protocol, there is a mixed content problem (yellow lock).
The problem is related to the fact that the reference to the gravatar contains https: //.
To solve the problem, have to change the function code: `xtd_comment_gravatar_url`
Maybe to make a separate setting switch the packet to work on HTTP or over HTTPS?

**Comment by danirus** [comment]
Thank you @pamost.
Fixed in ff55f37. 
The latest release 2.0.9, already in PyPI, includes the fix.

**Comment by pamost** [comment]
Thank you.
