### ISSUE TITLE
Handling of duplicate confirmations

### ISSUE THREAD

**Issue by ppershing** [danirus/django-comments-xtd#80]
When you click twice on the email link right now you end up with 404 which isn't very friendly because people freak out what is happening. There are two possible solutions

* just follow the original code path but don't create comment/send notifications. This will basically render the same thing on the second click making the user believe it is his/hers first click
* have a special template which says "comment was already submitted"

Personally, I prefer the first choice.

Additionally, when on the subject of confirmation, a request with bad signature might throw 400 Bad Request instead of 404 to make it clear what is happening (it took me quite a while to figure out why my `urls.py` do not match -- it turns out they match but`confirm` view throws 404)

**Comment by danirus** [comment]
I like the first solution too.

**Comment by danirus** [comment]
It's been resolved and fixed. 
It will be included with v2.8.1.
