### ISSUE TITLE
comment.user.is_authenticated()

### ISSUE THREAD

**Issue by j4n7** [danirus/django-comments-xtd#81]
Hi,

I was following the tutorial and tried posting a comment, logged in as 'admin' but I encountered this error:

File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\sitepackages\django_comments_xtd\views.py", line 103, in on_comment_was_posted
(comment.user and comment.user.is_authenticated())
TypeError: 'bool' object is not callable

I solved it deleting the '()' at the end, so instead of:
(comment.user and comment.user.is_authenticated**()**)

I wrote:

(comment.user and comment.user.is_authenticated)

Using Python3.5 and Django 2.0 (that needs some minor adjustments.

Thanks for this awesome package.

Bye,
Alejandro

**Comment by danirus** [comment]
@j4n7, thanks for the telling.

**Comment by danirus** [comment]
Fixed in e405dc790c986bd6dfe9b5bca1a2558bfb242981
