### ISSUE TITLE
COMMENTS_XTD_SEND_HTML_MAIL

### ISSUE THREAD

**Issue by IvoPo** [danirus/django-comments-xtd#83]
EDIT: I'm sorry i ssem to have copied the wrong line :(
[COMMENTS_XTD_CONFIRM_MAIL](https://github.com/danirus/django-comments-xtd/blob/master/docs/settings.rst#comments-xtd-confirm-mail)
in the example of the doc it says

`CCOMMENTS_XTD_CONFIRM_EMAIL = False`

which is it ? MAIL or EMAIL ?

I've both in my settings.py currently and it's still in the template and required.

cheers

**Comment by danirus** [comment]
The right form is `COMMENTS_XTD_SEND_HTML_EMAIL`.

**Comment by IvoPo** [comment]
I'm sorry it was about confirm_mail not html_mail.

**Comment by danirus** [comment]
No problem.
The right form is `COMMENTS_XTD_CONFIRM_EMAIL`.
I'll fix it in the docs, thanks for telling.

**Comment by danirus** [comment]
Fixed in e405dc790c986bd6dfe9b5bca1a2558bfb242981.
