### ISSUE TITLE
error message div showing when there is no errors

### ISSUE THREAD

**Issue by Tonyfoy** [danirus/django-comments-xtd#86]
I am following the tutorial and notice that in the comments/form.html(line 9-10). The div for error message is showing up when there is no errors. So there is a red empty div on the page. Is this normal? Or I missed something?
```
<div class="alert alert-danger hidden" data-comment-element="errors">
    </div>
```
<img width="689" alt="screen shot 2018-02-12 at 21 19 30" src="https://user-images.githubusercontent.com/36143195/36117748-10c56bfc-103b-11e8-9cd3-0fa0d7bc824b.png">

**Comment by danirus** [comment]
It's not expected. It might have something to do with the last changes.
If that's the problem, you could install the package with pip from PyPI.
Thanks for telling @Tonyfoy, I'll look into it tomorrow.

**Comment by Tonyfoy** [comment]
Hi @danirus, thanks for looking into it.

> If that's the problem, you could install the package with pip from PyPI.

I did install it with pip. Do you mean I should install an older version with pip?

**Comment by danirus** [comment]
I meant you could use the last version available in PyPI, but you are right, that version already has the last changes in master. If you need it immediately use 2.0.9 while I fix it. 
I will investigate this issue. Thanks again for the report.

**Comment by danirus** [comment]
In which step did you have this issue? I can't reproduce it. I however caught another error that might be related. I created a repository with the tutorial. Look at the commits, they match the sections in the tutorial. I will tag them but everything is in there.

The reason why this might happen is that the admin user doesn't have a name or email address. Add those attributes to the user through the admin interface and then try again. And please, let me know afterwards. Thanks @Tonyfoy!

**Comment by Tonyfoy** [comment]
I just figured it out. It was caused by Bootstrap 4. It is not an issue when using Bootstrap 3.3.7

**Comment by danirus** [comment]
Yes, I will update.

**Comment by Tonyfoy** [comment]
Hi danirus,
I was just wondering if this project will be updated to Bootstrap4?
Thanks

**Comment by danirus** [comment]
Hi @Tonyfoy,  it's something in the TODO list since v4 was launched.
I will give it a spin one of these days.
