### ISSUE TITLE
COMMENTS_XTD_MAX_THREAD_LEVEL_BY_MODEL not working

### ISSUE THREAD

**Issue by Tonyfoy** [danirus/django-comments-xtd#87]
I am following the tutorial>[ Different max thread levels](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#different-max-thread-levels) section. `COMMENTS_XTD_MAX_THREAD_LEVEL_BY_MODEL` does not work. The reply button only appears when `COMMENTS_XTD_MAX_THREAD_LEVEL` is set to greater than 0.

```
COMMENTS_XTD_MAX_THREAD_LEVEL = 0  # site wide default
COMMENTS_XTD_MAX_THREAD_LEVEL_BY_MODEL = {
    # Objects of the app blog, model post, can be nested
    # up to thread level 1.
        'blog.post': 1,
}
```

**Comment by SEGATON** [comment]
> It's a syntax error in the documentation. Use:
> 
>     * `COMMENTS_XTD_MAX_THREAD_LEVEL_BY_APP_MODEL` instead of
> 
>     * `COMMENTS_XTD_MAX_THREAD_LEVEL_BY_MODEL`
> 
> 
> I will fix it later today. Thank you @Tonyfoy.

still not working
