### ISSUE TITLE
Prerequisite for follow up notification?

### ISSUE THREAD

**Issue by sanastasiou** [danirus/django-comments-xtd#88]
Hi, awesome work. 

I just setup the plugin version of the package and it works great, but I have some question as I couldn't find any example in the documentation.

How does followup notification works? I would assume that the user model or something will have to have an e-mail field attached to it, or something similar. 

Also, when flagging a comment, and confirming the flag I am getting the following error:
'HttpResponseRedirect' object has no attribute 'startswith'
![2018-02-17_21h06_49](https://user-images.githubusercontent.com/2955627/36345190-7b5a38d2-1426-11e8-97fe-fd642fd96333.png)

Using django 1.11.4 if this is required.

P.S. Are there any other options in the plugin that we can use? I'll check the js code until then.

**Comment by danirus** [comment]
Hi @sanastasiou, thank you!

Yes, if the user sending the comment is a registered user and is authenticated but doesn't have an email address in the user object, django_comments_xtd will require the email address in the form. If the user is registered and has an email address then it's not required when sending the comment.
Be sure to sse the latest version, v2.1.0, it resolves a problem with that.

I'm sorry but the screenshot's error doesn't say much to me. It points to `django.contrib.contenttypes`, I don't see django_comments_xtd in the error stack (apart from the URL). Could you elaborate more? 

Did you try to follow the tutorial? It show case all the features. 
Notifications and comment redirection are at the beginning.

**Comment by sanastasiou** [comment]
@danirus Hi and thanks for the quick reply. I fixed the issue I had. My problem was, that the absolute URL wasn't a "reverse" for the associated object, rather a redirect. That was causing issues, when redirection from the comments-xtd links. Changing this to reverse solved my issues.

- OK, so if I understood correctly following scenarios can happen: Unregistered user needs verification for 
his e-mail to even be entered in DB ( if option is set in  settings.py. )

- If user has e-mail and he wants follow up notifications no other "field" is rendered.

- If user doesn't have e-mail and required followup notifications then an e-mail field will be rendered.

Please let me know if this is correct and close this non issue.

P.S. I am using latest version.

One last question -> how can I set the avatar to an image of my own? The avatar is taken from an http address which currently breaks our ssl certification plus I cannot use my own user's profile pictures. I haven't found any relevant option in the docs.

**Comment by sanastasiou** [comment]
@danirus Thanks for the answers. Yeah, I am not gonna remove the e-mail confirmation. OK, the use cases are exactly what I need. For the avatar, I'll check the app(s) -> I hope this will help prevent using the default image in the avatar.

One last question:

Is it possible to have the "notify me for updates" checkbox enabled by default? Or even better simply hide it and always have this functionality enabled?

**Comment by danirus** [comment]
Sorry. It's not implemented but you can do it.

Create a form that inherits from `XtdCommentForm` and use it with the setting `COMMENTS_XTD_FORM_CLASS`. See the docs [here](http://django-comments-xtd.readthedocs.io/en/latest/settings.html#comments-xtd-form-class).

In your class form be sure to make the `followup` field use a `HiddenInput` widget, and overwrite the `get_comment_create_data` so that it changes the `followup ` value to True in the data dictionary (see the current method [here](https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/forms.py#L52)).

**Comment by sanastasiou** [comment]
@danirus I did that however I see no change at all in the form. Is this setting even relevant when using the .js plugin?

**Comment by sanastasiou** [comment]
I finished following this: https://github.com/danirus/django-comments-xtd/blob/master/docs/javascript.rst

If you tell me how create my own bundle then I adjust the form to my own needs.

**Comment by sanastasiou** [comment]
Ah, I missed the last part of docu!! Trying to build it now 👍

**Comment by sanastasiou** [comment]
Running webpack --watch throws some kind of exception and I cannot build unfortunately. I am on windows 10 if this makes any difference.

`C:\Work\Django-Comment-Xtd\django-comments-xtd>webpack
(node:14048) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\lib\Chunk.js:438
                throw new Error("Chunk.parents: Use ChunkGroup.getParents() instead");
                ^

Error: Chunk.parents: Use ChunkGroup.getParents() instead
    at Chunk.get (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\lib\Chunk.js:438:9)
    at CommonsChunkPlugin.getAffectedChunks (C:\Work\Django-Comment-Xtd\django-comments-xtd\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:229:17)
    at targetChunks.forEach (C:\Work\Django-Comment-Xtd\django-comments-xtd\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:107:34)
    at Array.forEach (native)
    at compilation.plugin (C:\Work\Django-Comment-Xtd\django-comments-xtd\node_modules\webpack\lib\optimize\CommonsChunkPlugin.js:102:18)
    at SyncBailHook.eval (eval at create (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook [as _call] (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:874:30)
    at hooks.make.callAsync.err (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\lib\Compiler.js:464:17)
    at _done (eval at create (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err0 (eval at create (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:20:22)
    at _addModuleChain (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:749:12)
    at processModuleDependencies.err (C:\Users\stefa\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by sanastasiou** [comment]
@danirus Could you please help here? Do I need to build in ubuntu? I really need to modify the layout of the comments for our projects :)..

**Comment by danirus** [comment]
@sanastasiou, check the branch [issue-88](https://github.com/danirus/django-comments-xtd/compare/issue-88). Those changes will set `follow_up = True`. Remeber to run `webpack -p` to build the plugin without the follow-up field.

**Comment by tanveerahmad1517** [comment]
@sanastasiou Please did you find solution for avatar if you solved avatar problem Please share with me how did you done this I don't want default avatar picture on user Please help me :(

**Comment by danirus** [comment]
Hi @tanveerahmad1517, @sanastasiou, did you find a solution for the avatar issue?
I just realize this issue is still in the code. It shows up when using the JavaScript plugin.
The issue is in the serializer `ReadCommentSerializer`, in the method [`get_user_avatar`](https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/api/serializers.py#L247).

**Comment by danirus** [comment]
The `get_user_avatar` issue is fixed already. 
I added a use case to cover how you can use different apps to provide user's avatars in comments. You can read the use case here: [Change user image or avatar](https://django-comments-xtd.readthedocs.io/en/latest/usecases/change-user-image-or-avatar.html).

About making the `follow_up = True` by default in the form, did you manage to do it?

**Comment by danirus** [comment]
Regarding the follow_up, I created the issue #206 to implement a new setting for the value of the follow_up field.
