### ISSUE TITLE
The gravatar

### ISSUE THREAD

**Issue by nicoodakp** [danirus/django-comments-xtd#90]
![capture](https://user-images.githubusercontent.com/36462624/36639140-abbd6cd0-19d3-11e8-83f7-87f9f189165c.JPG)

Hi, really love the package. thanks a lot. For some reason the gravatar were a little bit off. (where the media left should have some gap btw media content ?) super new to this and not sure if im doing it correctly.

`{% extends "posts/post-base.html" %}
{% load staticfiles %}

<div class="container-fluid">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

			{% block title %}<a href="{{post.id}}"><h1><p class="text-white">{{ post.title }}</p></h1></a>
			<p class="text-white"> {{ post.updated }} </p>{% endblock %}
			{% block content %}
				<div class = "container">
						<div class="row">
								<div class="col-lg-8 col-md-10 mx-auto">
					<p>{{ post.body|safe|linebreaks}}</p>

					<hr>

                  <button type="button" class="btn btn-primary float-lg-right" onclick="goBack()">Go Back</button>
                  <script>
                      function goBack() {
                          window.history.back();
                      }
                      </script>
        </div>
           </div>
                </div>
<div class = "container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
{% load comments %}
{% load comments_xtd %}
<div id="comments">
  {% get_comment_count for object as comment_count %}
  {% if comment_count %}
  <H5 class="text-center">

  </H5>
  <hr/>
  {% endif %}

  {% if object.allow_comments %}
  <div class="comment">
    <H4 class="text-center">Post your comment</H4>
    <div class="well">
      {% render_comment_form for object %}
    </div>
  </div>
  {% else %}
  <h5 class="text-center">comments are disabled for this article</h5>
  {% endif %}

  {% if comment_count %}
  <hr/>
  <ul class="media-list" id="comment-list">
    {% render_xtdcomment_tree for object %}
  </ul>
  {% endif %}
</div>
      </div>
   </div>
</div>

{% endblock %}

		</div>
	</div>
</div>
`

**Comment by danirus** [comment]
Thanks @nicoodakp. It seems you are not loading the default css file provided with django-comments-xtd.

Take a look at the [preparation](http://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#preparation) section in the documentation. It's part of the tutorial. I recommend you to follow the tutorial. You can also look at the code behind the demo sites. In all those cases I use the Bootstrap UI framework.

**Comment by nicoodakp** [comment]
Thanks for the notice, I follow the example to put the href static into the html and the tree works now. but at the same time it undermine the whole page structure.....my website is currently using bootstrap 4 alpha and i saw your css was using boot 3.3.  is there anyway to get around with this ?
many thanks

**Comment by nicoodakp** [comment]
never mind i think i got it. i change the comment_tree.html to class="align-self-start mr-3" at line 10. it works now.
